import type {
  ActiveTradeView,
  AlertEnvelope,
  AssetContextView,
  BacktestDetailView,
  BacktestListView,
  BarView,
  BrokerAdapterSnapshotView,
  CommandCenterStatusView,
  DailyBriefingView,
  DeskSummaryView,
  DegradedSourceView,
  DataRealityView,
  HealthView,
  HomeOperatorSummaryView,
  JournalReviewView,
  ManualFillView,
  NewsView,
  OpsActionView,
  OpsSummaryView,
  OperationalBacklogView,
  PilotDashboardView,
  PilotExportResponse,
  PilotMetricSummaryView,
  PilotSummaryView,
  OpportunityHunterView,
  PaperTradeAnalyticsView,
  PaperTradeDetailView,
  PaperTradeReviewView,
  PaperTradeView,
  ResearchView,
  ReviewSummaryView,
  ReviewTaskView,
  RibbonView,
  RiskDetailView,
  RiskExposureView,
  RiskView,
  SessionOverviewView,
  ExecutionGateView,
  AdapterHealthView,
  AuditLogView,
  SignalDetailView,
  SignalsSummaryView,
  SignalView,
  StrategyDriftWarningView,
  StrategyDetailView,
  StrategyListView,
  TradeTicketDetailView,
  TicketSummaryView,
  TradeTicketView,
  WalletBalanceView,
  WeeklyReviewView,
  WatchlistView,
} from "../types/api";

export const mockHealth: HealthView = {
  status: "mock",
  sqlite_path: "mock/sqlite.db",
  duckdb_path: "mock/analytics.duckdb",
  parquet_dir: "mock/parquet",
};

const btcDataReality: DataRealityView = {
  provenance: {
    symbol: "BTC",
    underlying_asset: "BTC",
    research_symbol: "BTCUSD",
    tradable_symbol: "BTCUSD",
    intended_venue: "binance_spot",
    intended_instrument: "spot_pair",
    source_name: "fixture_bars",
    source_type: "fixture",
    source_timing: "fixture",
    freshness_sla_minutes: 1440,
    realism_grade: "B",
    proxy_mapping_notes: "Direct crypto spot mapping in fixture mode.",
    asset_class: "crypto",
  },
  freshness_minutes: 5,
  freshness_state: "fresh",
  event_recency_minutes: null,
  realism_score: 48,
  ranking_penalty: 38,
  promotion_blocked: false,
  alert_allowed: true,
  execution_suitability: "research_only",
  news_suitability: "research_only",
  ui_warning: "Current context is running in deterministic fixture-first mode.",
  timing_semantics_note: "Fixture timing semantics support deterministic local testing only.",
  event_context_note: "",
  penalties: [
    {
      code: "fixture_only",
      severity: "warning",
      summary: "Current context is running in deterministic fixture-first mode.",
      score_penalty: 14,
    },
    {
      code: "fixture_source",
      severity: "info",
      summary: "Source is fixture-backed rather than exchange-verified.",
      score_penalty: 18,
    },
    {
      code: "timing_fixture",
      severity: "info",
      summary: "Fixture timing semantics support deterministic local testing only.",
      score_penalty: 6,
    },
  ],
  tradable_alignment_note: "BTC research symbol BTCUSD aligns directly with BTCUSD on binance_spot.",
};

const ethDataReality: DataRealityView = {
  provenance: {
    symbol: "ETH",
    underlying_asset: "ETH",
    research_symbol: "ETHUSD",
    tradable_symbol: "ETHUSD",
    intended_venue: "binance_spot",
    intended_instrument: "spot_pair",
    source_name: "fixture_bars",
    source_type: "fixture",
    source_timing: "fixture",
    freshness_sla_minutes: 1440,
    realism_grade: "B",
    proxy_mapping_notes: "Direct crypto spot mapping in fixture mode.",
    asset_class: "crypto",
  },
  freshness_minutes: 5,
  freshness_state: "fresh",
  event_recency_minutes: null,
  realism_score: 42,
  ranking_penalty: 44,
  promotion_blocked: true,
  alert_allowed: true,
  execution_suitability: "research_only",
  news_suitability: "research_only",
  ui_warning: "Current context is running in deterministic fixture-first mode.",
  timing_semantics_note: "Fixture timing semantics support deterministic local testing only.",
  event_context_note: "",
  penalties: [
    {
      code: "fixture_only",
      severity: "warning",
      summary: "Current context is running in deterministic fixture-first mode.",
      score_penalty: 14,
    },
    {
      code: "fixture_source",
      severity: "info",
      summary: "Source is fixture-backed rather than exchange-verified.",
      score_penalty: 18,
    },
    {
      code: "timing_fixture",
      severity: "info",
      summary: "Fixture timing semantics support deterministic local testing only.",
      score_penalty: 6,
    },
    {
      code: "missing_cross_asset_confirmation",
      severity: "info",
      summary: "Cross-asset confirmation is weak or missing in the latest context.",
      score_penalty: 6,
    },
  ],
  tradable_alignment_note: "ETH research symbol ETHUSD aligns directly with ETHUSD on binance_spot.",
};

const wtiDataReality: DataRealityView = {
  provenance: {
    symbol: "WTI",
    underlying_asset: "WTI",
    research_symbol: "WTI_CTX",
    tradable_symbol: "USO",
    intended_venue: "nyse_arca",
    intended_instrument: "etf_proxy",
    source_name: "macro_fixture_proxy",
    source_type: "proxy",
    source_timing: "end_of_day",
    freshness_sla_minutes: 1440,
    realism_grade: "E",
    proxy_mapping_notes: "WTI research uses contextual proxy bars and should not be treated like direct CL futures pricing.",
    asset_class: "commodity",
  },
  freshness_minutes: 10,
  freshness_state: "fresh",
  event_recency_minutes: 80,
  realism_score: 0,
  ranking_penalty: 116,
  promotion_blocked: true,
  alert_allowed: false,
  execution_suitability: "context_only",
  news_suitability: "news_context_only",
  ui_warning:
    "WTI research uses contextual proxy bars and should not be treated like direct CL futures pricing. | End-of-day timing semantics support swing research but not intraday execution claims. | Research symbol WTI_CTX and underlying WTI are aligned through tradable proxy USO.",
  timing_semantics_note: "End-of-day timing semantics support swing research but not intraday execution claims.",
  event_context_note:
    "EIA schedule awareness: weekly petroleum context is anchored to the Wednesday 10:30 ET release window; the latest local EIA item is 80 minutes old and is inside or near the latest EIA release window.",
  penalties: [
    {
      code: "fixture_only",
      severity: "warning",
      summary: "Current context is running in deterministic fixture-first mode.",
      score_penalty: 18,
    },
    {
      code: "proxy_grade_mapping",
      severity: "warning",
      summary: "WTI research uses contextual proxy bars and should not be treated like direct CL futures pricing.",
      score_penalty: 14,
    },
    {
      code: "timing_end_of_day",
      severity: "warning",
      summary: "End-of-day timing semantics support swing research but not intraday execution claims.",
      score_penalty: 14,
    },
    {
      code: "tradable_mismatch",
      severity: "warning",
      summary: "Research symbol WTI_CTX and underlying WTI are aligned through tradable proxy USO.",
      score_penalty: 12,
    },
    {
      code: "contextual_price_only",
      severity: "warning",
      summary: "Current series is suitable for contextual research, not direct execution benchmarking.",
      score_penalty: 10,
    },
    {
      code: "timing_too_weak_for_intraday",
      severity: "warning",
      summary: "Price timing is too weak for intraday-style execution claims on this asset class.",
      score_penalty: 10,
    },
    {
      code: "missing_cross_asset_confirmation",
      severity: "info",
      summary: "Cross-asset confirmation is weak or missing in the latest context.",
      score_penalty: 6,
    },
    {
      code: "weak_oil_realism",
      severity: "critical",
      summary: "Oil context is materially weaker than direct venue-grade futures data.",
      score_penalty: 20,
    },
    {
      code: "oil_release_window_proxy",
      severity: "critical",
      summary: "Recent EIA release context is useful for news interpretation, but the current oil price mapping is not intraday-execution-suitable.",
      score_penalty: 12,
    },
  ],
  tradable_alignment_note: "WTI research symbol WTI_CTX is mapped to tradable proxy USO on nyse_arca.",
};

export const mockRibbon: RibbonView = {
  macro_regime: "event-risk",
  data_freshness_minutes: 22,
  freshness_status: "fresh",
  risk_budget_used_pct: 1.1,
  risk_budget_total_pct: 2.5,
  pipeline_status: "completed",
  source_mode: "sample",
  last_refresh: "2026-03-15T11:30:00Z",
  next_event: {
    title: "US CPI Release",
    impact: "high",
    event_time: "2026-03-15T12:30:00Z",
  },
};

export const mockSignals: SignalView[] = [
  {
    signal_id: "sig_8dca021b9c1256658b09a4fa6e218485",
    symbol: "BTC",
    signal_type: "trend_breakout",
    timestamp: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
    direction: "long",
    score: 74.6,
    confidence: 0.79,
    noise_probability: 0.22,
    thesis: "Breakout above the 20-day range remains intact with aligned structure and supportive volume.",
    invalidation: 68450,
    targets: { base: 73120, stretch: 74840 },
    uncertainty: 0.21,
    data_quality: "fixture",
    affected_assets: ["BTC", "ETH"],
    features: { close: 71880, atr_14: 1720, trend_state: "uptrend", relative_volume: 1.22, breakout_distance: 0.018, cross_asset_positive: ["ETH"] },
    data_reality: btcDataReality,
  },
  {
    signal_id: "sig_342ef03a8f4a559b9b1773fc5fd9f4ae",
    symbol: "ETH",
    signal_type: "event_driven",
    timestamp: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
    direction: "neutral",
    score: 31.4,
    confidence: 0.58,
    noise_probability: 0.41,
    thesis: "CPI is inside the event window. Continuation setups should be treated as event-sensitive until the release clears.",
    invalidation: 3440,
    targets: { base: 3745, stretch: 3810 },
    uncertainty: 0.42,
    data_quality: "fixture",
    affected_assets: ["ETH", "BTC"],
    features: { close: 3588, atr_14: 104, trend_state: "uptrend", relative_volume: 0.96, breakout_distance: 0.007, cross_asset_positive: [] },
    data_reality: ethDataReality,
  },
];

export const mockHighRiskSignals = mockSignals.filter((row) => row.noise_probability >= 0.35);

export const mockNews: NewsView[] = [
  {
    source: "EIA",
    published_at: "2026-03-15T10:10:00Z",
    freshness_minutes: 80,
    title: "Crude inventory draw tightens inflation-sensitive macro backdrop",
    summary: "Energy-led inflation context remains relevant for rates, dollar sensitivity, and crypto beta positioning.",
    url: "https://www.eia.gov/petroleum/supply/weekly/",
    tags: ["oil", "inflation", "macro"],
    entity_tags: ["oil", "inflation", "macro", "WTI", "US10Y", "BTC", "ETH"],
    affected_assets: ["WTI", "US10Y", "BTC", "ETH"],
    data_quality: "fixture",
  },
  {
    source: "FRED",
    published_at: "2026-03-15T09:00:00Z",
    freshness_minutes: 150,
    title: "CPI release due within the next hour",
    summary: "High-impact inflation data can reset rate expectations, dollar pricing, and crypto risk appetite.",
    url: "https://fred.stlouisfed.org/",
    tags: ["cpi", "rates", "macro"],
    entity_tags: ["cpi", "rates", "macro", "BTC", "ETH", "DXY", "US10Y"],
    affected_assets: ["BTC", "ETH", "DXY", "US10Y"],
    data_quality: "fixture",
  },
];

export const mockWatchlist: WatchlistView[] = [
  {
    symbol: "BTC",
    label: "Bitcoin",
    thesis: "Primary crypto beta with the cleanest breakout structure.",
    priority: 1,
    status: "active",
    last_signal_score: 74.6,
    updated_at: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
  },
  {
    symbol: "ETH",
    label: "Ethereum",
    thesis: "Watch for confirmation after the macro event clears.",
    priority: 2,
    status: "active",
    last_signal_score: 31.4,
    updated_at: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
  },
  {
    symbol: "WTI",
    label: "WTI Crude",
    thesis: "Macro scout asset for inflation spillover.",
    priority: 3,
    status: "context",
    last_signal_score: 0,
    updated_at: "2026-03-15T11:20:00Z",
    freshness_minutes: 10,
  },
];

export const mockResearch: ResearchView[] = [
  {
    symbol: "BTC",
    label: "BTC",
    timeframe: "1d",
    last_price: 71880,
    return_1d_pct: 1.42,
    return_5d_pct: 4.9,
    trend_state: "uptrend",
    relative_volume: 1.22,
    atr_pct: 2.4,
    breakout_distance: 1.8,
    structure_score: 2.4,
    data_quality: "fixture",
    data_reality: btcDataReality,
  },
  {
    symbol: "ETH",
    label: "ETH",
    timeframe: "1d",
    last_price: 3588,
    return_1d_pct: -0.6,
    return_5d_pct: 2.1,
    trend_state: "uptrend",
    relative_volume: 0.96,
    atr_pct: 2.9,
    breakout_distance: 0.7,
    structure_score: 1.4,
    data_quality: "fixture",
    data_reality: ethDataReality,
  },
  {
    symbol: "WTI",
    label: "WTI",
    timeframe: "1d",
    last_price: 79.2,
    return_1d_pct: 0.4,
    return_5d_pct: 1.2,
    trend_state: "range",
    relative_volume: 1.08,
    atr_pct: 1.9,
    breakout_distance: 0.2,
    structure_score: 0.8,
    data_quality: "fixture",
    data_reality: wtiDataReality,
  },
];

export const mockRisk: RiskView[] = [
  {
    risk_report_id: "risk_28782b441c135ccf921f5dbc7f3d6d77",
    signal_id: mockSignals[0].signal_id,
    symbol: "BTC",
    as_of: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
    stop_price: 68450,
    size_band: "medium",
    max_portfolio_risk_pct: 0.7,
    exposure_cluster: "crypto_beta",
    uncertainty: 0.21,
    data_quality: "fixture",
    scenario_shocks: { risk_off_pct: -8, liquidity_gap_pct: -4.5, macro_repricing_pct: -6 },
    report: { entry_reference: 71880, atr_14: 1720, risk_notes: ["No live execution enabled."] },
    data_reality: btcDataReality,
  },
  {
    risk_report_id: "risk_3490fc4bf0305fbcbe6c1765fcc4fed8",
    signal_id: mockSignals[1].signal_id,
    symbol: "ETH",
    as_of: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
    stop_price: 3440,
    size_band: "small",
    max_portfolio_risk_pct: 0.4,
    exposure_cluster: "crypto_beta",
    uncertainty: 0.42,
    data_quality: "fixture",
    scenario_shocks: { risk_off_pct: -10.5, liquidity_gap_pct: -5.8, macro_repricing_pct: -7.2 },
    report: { entry_reference: 3588, atr_14: 104, risk_notes: ["Reduce conviction near CPI."] },
    data_reality: ethDataReality,
  },
];

export const mockRiskExposure: RiskExposureView[] = [
  {
    cluster: "crypto_beta",
    symbols: ["BTC", "ETH"],
    gross_risk_pct: 1.1,
    worst_scenario_pct: -10.5,
  },
];

const mockTrendPenalties = [
  {
    code: "fixture_only",
    severity: "warning",
    summary: "Current validation depends on fixture-first market data.",
    score_penalty: 14,
  },
  {
    code: "fixture_source",
    severity: "info",
    summary: "Source is fixture-backed rather than exchange-verified.",
    score_penalty: 18,
  },
  {
    code: "timing_fixture",
    severity: "info",
    summary: "Fixture timing semantics support deterministic local testing only.",
    score_penalty: 6,
  },
  {
    code: "missing_cross_asset_confirmation",
    severity: "info",
    summary: "Cross-asset confirmation is weak or missing in the latest context.",
    score_penalty: 6,
  },
];

const mockCalibrationSummary = [
  {
    strategy_name: "trend_breakout_v1",
    created_at: "2026-03-15T11:30:00Z",
    bucket_kind: "score",
    buckets: [
      { bucket: "top", sample_size: 3, avg_score: 74.6, avg_confidence: 0.79, hit_rate: 0.67, expectancy_proxy: 1.0, invalidation_rate: 0, target_attainment: 0.67 },
      { bucket: "middle", sample_size: 0, avg_score: 0, avg_confidence: 0, hit_rate: 0, expectancy_proxy: 0, invalidation_rate: 0, target_attainment: 0 },
      { bucket: "low", sample_size: 0, avg_score: 0, avg_confidence: 0, hit_rate: 0, expectancy_proxy: 0, invalidation_rate: 0, target_attainment: 0 },
    ],
    notes: "Calibration compares buckets only. It is not a probability-of-profit claim.",
  },
  {
    strategy_name: "trend_breakout_v1",
    created_at: "2026-03-15T11:30:00Z",
    bucket_kind: "confidence",
    buckets: [
      { bucket: "top", sample_size: 3, avg_score: 74.6, avg_confidence: 0.79, hit_rate: 0.67, expectancy_proxy: 1.0, invalidation_rate: 0, target_attainment: 0.67 },
      { bucket: "middle", sample_size: 0, avg_score: 0, avg_confidence: 0, hit_rate: 0, expectancy_proxy: 0, invalidation_rate: 0, target_attainment: 0 },
      { bucket: "low", sample_size: 0, avg_score: 0, avg_confidence: 0, hit_rate: 0, expectancy_proxy: 0, invalidation_rate: 0, target_attainment: 0 },
    ],
    notes: "Calibration compares buckets only. It is not a probability-of-profit claim.",
  },
];

export const mockSignalDetail: SignalDetailView = {
  ...mockSignals[0],
  evidence: [
    {
      label: "Breakout distance",
      value: "1.8%",
      verdict: "supportive",
      note: "Distance above the recent breakout level.",
    },
    {
      label: "Relative volume",
      value: "1.22x",
      verdict: "supportive",
      note: "Current volume is above the 20-bar baseline.",
    },
  ],
  catalyst_news: mockNews,
  related_risk: mockRisk[0],
  freshness_status: "fresh",
};

export const mockRiskDetail: RiskDetailView = {
  ...mockRisk[0],
  linked_signal: mockSignals[0],
  stop_logic: {
    method: "atr_multiple",
    entry_reference: 71880,
    atr_14: 1720,
    stop_price: 68450,
    distance: 3430,
  },
  risk_notes: ["No live execution enabled."],
  cluster_exposure: mockRiskExposure[0],
  freshness_status: "fresh",
};

export const mockOpportunities: OpportunityHunterView = {
  generated_at: "2026-03-15T11:30:00Z",
  focus_queue: [
    {
      symbol: "BTC",
      label: "Bitcoin",
      queue: "focus",
      score: 90.45,
      score_decomposition: {
        signal_score: 74.6,
        confidence_bonus: 11.85,
        trend_bonus: 6,
        noise_penalty: 3.96,
        freshness_penalty: 0.08,
        realism_penalty: 38,
      },
      promotion_reasons: ["signal_score_above_focus_threshold", "trend_state_uptrend", "risk_budget_acceptable"],
      freshness_minutes: 5,
      risk_notes: ["No live execution enabled."],
      signal_id: mockSignals[0].signal_id,
      risk_report_id: mockRisk[0].risk_report_id,
      status: "active",
      data_reality: btcDataReality,
    },
  ],
  scout_queue: [
    {
      symbol: "ETH",
      label: "Ethereum",
      queue: "scout",
      score: 39.4,
      score_decomposition: {
        signal_score: 31.4,
        confidence_bonus: 8.7,
        trend_bonus: 6,
        noise_penalty: 7.38,
        freshness_penalty: 0.08,
        realism_penalty: 44,
      },
      promotion_reasons: ["trend_state_uptrend", "awaiting_confirmation"],
      freshness_minutes: 5,
      risk_notes: ["Reduce conviction near CPI."],
      signal_id: mockSignals[1].signal_id,
      risk_report_id: mockRisk[1].risk_report_id,
      status: "active",
      data_reality: ethDataReality,
    },
  ],
};

export const mockBars: Record<string, BarView[]> = {
  BTC: [
    { symbol: "BTC", timestamp: "2026-03-11T00:00:00Z", open: 69210, high: 69920, low: 68880, close: 69740, volume: 22800 },
    { symbol: "BTC", timestamp: "2026-03-12T00:00:00Z", open: 69740, high: 70640, low: 69520, close: 70420, volume: 24100 },
    { symbol: "BTC", timestamp: "2026-03-13T00:00:00Z", open: 70420, high: 71310, low: 70110, close: 70980, volume: 25220 },
    { symbol: "BTC", timestamp: "2026-03-14T00:00:00Z", open: 70980, high: 72140, low: 70710, close: 71880, volume: 26740 },
  ],
  ETH: [
    { symbol: "ETH", timestamp: "2026-03-11T00:00:00Z", open: 3522, high: 3570, low: 3498, close: 3554, volume: 140200 },
    { symbol: "ETH", timestamp: "2026-03-12T00:00:00Z", open: 3554, high: 3638, low: 3531, close: 3622, volume: 146400 },
    { symbol: "ETH", timestamp: "2026-03-13T00:00:00Z", open: 3622, high: 3640, low: 3572, close: 3588, volume: 131100 },
    { symbol: "ETH", timestamp: "2026-03-14T00:00:00Z", open: 3588, high: 3612, low: 3525, close: 3566, volume: 125480 },
  ],
  WTI: [
    { symbol: "WTI", timestamp: "2026-03-11T00:00:00Z", open: 78.1, high: 79.0, low: 77.8, close: 78.6, volume: 7120 },
    { symbol: "WTI", timestamp: "2026-03-12T00:00:00Z", open: 78.6, high: 79.3, low: 78.2, close: 79.0, volume: 7340 },
    { symbol: "WTI", timestamp: "2026-03-13T00:00:00Z", open: 79.0, high: 79.7, low: 78.7, close: 79.2, volume: 7280 },
    { symbol: "WTI", timestamp: "2026-03-14T00:00:00Z", open: 79.2, high: 79.6, low: 78.4, close: 78.9, volume: 7400 },
  ],
};

export const mockAssetContexts: Record<string, AssetContextView> = {
  BTC: {
    symbol: "BTC",
    latest_signal: mockSignals[0],
    latest_risk: mockRisk[0],
    research: mockResearch[0],
    related_news: mockNews,
    latest_backtest: {
      id: 7,
      strategy_name: "trend_breakout_v1",
      engine: "strategy_lab",
      status: "completed",
      symbol: "BTC",
      timeframe: "1d",
      created_at: "2026-03-15T10:45:00Z",
      proxy_grade: false,
      promoted_candidate: false,
      search_method: "grid",
      robustness_score: 71.4,
      net_return_pct: 14.2,
      sharpe_ratio: 1.18,
      max_drawdown_pct: -8.6,
      trade_count: 7,
      lifecycle_state: "promoted",
      data_realism_penalties: mockTrendPenalties,
      data_reality: btcDataReality,
    },
    data_reality: btcDataReality,
  },
  ETH: {
    symbol: "ETH",
    latest_signal: mockSignals[1],
    latest_risk: mockRisk[1],
    research: mockResearch[1],
    related_news: mockNews,
    latest_backtest: null,
    data_reality: ethDataReality,
  },
  WTI: {
    symbol: "WTI",
    latest_signal: null,
    latest_risk: null,
    research: mockResearch[2],
    related_news: mockNews.filter((item) => item.affected_assets.includes("WTI")),
    latest_backtest: null,
    data_reality: wtiDataReality,
  },
};

export const mockActiveTrades: ActiveTradeView[] = [
  {
    trade_id: "trade_c5093f1b8d175f7e9ac0e6a5fd6151f8",
    symbol: "BTC",
    strategy_name: "trend_breakout_v1",
    side: "long",
    entry_time: "2026-03-12T10:30:00Z",
    entry_price: 70420,
    current_price: 71880,
    stop_price: 68450,
    target_price: 74200,
    pnl_pct: 2.07,
    size_band: "medium",
    status: "open",
    thesis: "Breakout structure remains valid above invalidation.",
    data_quality: "fixture",
    signal_id: mockSignals[0].signal_id,
    risk_report_id: mockRisk[0].risk_report_id,
    notes: "Trim size if CPI lands hotter than expected.",
    updated_at: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
  },
];

const btcProposedAdherence = {
  entered_inside_suggested_zone: null,
  invalidation_respected: null,
  time_stop_respected: null,
  realism_warning_ignored: null,
  size_plan_respected: null,
  exited_per_plan: null,
  adherence_score: 0,
  breached_rules: [],
};

const ethOpenAdherence = {
  entered_inside_suggested_zone: true,
  invalidation_respected: null,
  time_stop_respected: null,
  realism_warning_ignored: null,
  size_plan_respected: true,
  exited_per_plan: null,
  adherence_score: 1,
  breached_rules: [],
};

const btcClosedAdherence = {
  entered_inside_suggested_zone: true,
  invalidation_respected: true,
  time_stop_respected: null,
  realism_warning_ignored: false,
  size_plan_respected: true,
  exited_per_plan: true,
  adherence_score: 1,
  breached_rules: [],
};

const ethInvalidatedAdherence = {
  entered_inside_suggested_zone: true,
  invalidation_respected: false,
  time_stop_respected: null,
  realism_warning_ignored: true,
  size_plan_respected: false,
  exited_per_plan: false,
  adherence_score: 0.25,
  breached_rules: ["invalidation_respected", "realism_warning_ignored", "size_plan_respected", "exited_per_plan"],
};

const btcExecutionRealism = {
  entry_slippage_bps: 10,
  stop_slippage_bps: 16,
  target_fill_mode: "conservative_touch",
  gap_through_stop_flag: false,
  event_latency_penalty: 0,
  delayed_source_penalty: 6,
  effective_entry: 70690.62,
  effective_stop: 68340.48,
  fill_note: "Execution realism is deterministic and local-only; it is not a real fill record. Current data reality is research_only.",
};

const ethExecutionRealism = {
  entry_slippage_bps: 10,
  stop_slippage_bps: 18,
  target_fill_mode: "conservative_touch",
  gap_through_stop_flag: false,
  event_latency_penalty: 14,
  delayed_source_penalty: 6,
  effective_entry: 3606.51,
  effective_stop: 3433.81,
  fill_note: "Execution realism is deterministic and local-only; it is not a real fill record. Current data reality is research_only.",
};

const btcExecutionQuality = {
  signal_quality: "strong",
  plan_quality: "context_limited",
  execution_quality: "clean",
  slippage_penalty_bps: 26,
  latency_penalty: 0,
  delayed_penalty: 6,
  notes: [
    "Signal bucket uses score 74.6 and noise 0.22.",
    "BTC research symbol BTCUSD aligns directly with BTCUSD on binance_spot.",
  ],
};

const ethExecutionQuality = {
  signal_quality: "fragile",
  plan_quality: "context_limited",
  execution_quality: "penalized",
  slippage_penalty_bps: 28,
  latency_penalty: 14,
  delayed_penalty: 6,
  notes: [
    "Signal bucket uses score 31.4 and noise 0.41.",
    "ETH research symbol ETHUSD aligns directly with ETHUSD on binance_spot.",
  ],
};

const btcScenarioStress = [
  { scenario: "btc_down", entity_type: "paper_trade", entity_id: "paper_trade_closed_btc", symbol: "BTC", severity: "critical", shock_pct: -8, pnl_impact_pct: -8, confidence_impact: 0.43, rationale: "BTC stress uses deterministic btc_down shock with base confidence 0.79." },
  { scenario: "oil_spike", entity_type: "paper_trade", entity_id: "paper_trade_closed_btc", symbol: "BTC", severity: "info", shock_pct: -1.2, pnl_impact_pct: -1.2, confidence_impact: 0.08, rationale: "BTC stress uses deterministic oil_spike shock with base confidence 0.79." },
  { scenario: "dxy_up", entity_type: "paper_trade", entity_id: "paper_trade_closed_btc", symbol: "BTC", severity: "warning", shock_pct: -4.5, pnl_impact_pct: -4.5, confidence_impact: 0.23, rationale: "BTC stress uses deterministic dxy_up shock with base confidence 0.79." },
];

const btcTimeline = {
  trade_id: "paper_trade_closed_btc",
  symbol: "BTC",
  generated_at: "2026-03-15T11:30:00Z",
  pre_event: [
    { timestamp: "2026-03-15T11:25:00Z", phase: "pre_event", event_type: "signal", title: "BTC trend_breakout", note: mockSignals[0].thesis, price: 71880, related_alert_ids: [] },
    { timestamp: "2026-03-15T11:25:00Z", phase: "pre_event", event_type: "risk", title: "BTC risk report", note: "Size band medium, stop 68450.00.", price: 68450, related_alert_ids: [] },
  ],
  event_trigger: [],
  post_event: [{ timestamp: "2026-03-15T11:25:00Z", phase: "post_event", event_type: "alert", title: "BTC signal created", note: "Breakout above the 20-day range remains intact with aligned structure and supportive volume.", price: null, related_alert_ids: ["alert_1"] }],
  trade_actions: [
    { timestamp: "2026-03-11T09:55:00Z", phase: "trade_action", event_type: "proposed", title: "BTC proposed", note: "Proposed from BTC signal.", price: null, related_alert_ids: ["alert_1"] },
    { timestamp: "2026-03-11T10:30:00Z", phase: "trade_action", event_type: "opened", title: "BTC opened", note: "Opened after intraday reclaim.", price: 70620, related_alert_ids: ["alert_1"] },
    { timestamp: "2026-03-12T14:00:00Z", phase: "trade_action", event_type: "closed_win", title: "BTC closed_win", note: "Closed at base target.", price: 73150, related_alert_ids: ["alert_1"] },
  ],
  progression: [
    { timestamp: "2026-03-11T10:30:00Z", phase: "progression", event_type: "pre_event_state", title: "Initial post-entry state", note: "Opened near 70620.00.", price: 70620, related_alert_ids: [] },
    { timestamp: "2026-03-12T14:00:00Z", phase: "progression", event_type: "post_event_state", title: "Latest tracked state", note: "Last tracked close 73150.00.", price: 73150, related_alert_ids: [] },
    { timestamp: "2026-03-12T14:00:00Z", phase: "progression", event_type: "target_progress", title: "Target progression", note: "Base target 73120.00, stretch 74840.00.", price: 73120, related_alert_ids: [] },
  ],
};

export const mockPaperTradesProposed: PaperTradeView[] = [
  {
    trade_id: "paper_trade_proposed_btc",
    signal_id: mockSignals[0].signal_id,
    risk_report_id: mockRisk[0].risk_report_id,
    strategy_id: "trend_breakout_v1",
    symbol: "BTC",
    side: "long",
    proposed_entry_zone: { low: 71320, high: 72440 },
    actual_entry: null,
    stop: 68450,
    targets: { base: 73120, stretch: 74840 },
    size_plan: { size_band: "medium", max_portfolio_risk_pct: 0.7 },
    actual_size: 0,
    status: "proposed",
    opened_at: null,
    closed_at: null,
    close_reason: "",
    close_price: null,
    notes: "Candidate breakout entry queued from the ranked BTC signal.",
    freshness_minutes: 4,
    data_quality: "fixture",
    lifecycle_events: [
      { status: "proposed", note: "Proposed from BTC trend breakout signal.", timestamp: "2026-03-15T11:26:00Z" },
    ],
    outcome: {
      entry_quality_label: "pending",
      entry_zone_delta_pct: 0,
      stop_adherence: true,
      target_attainment: "none",
      time_to_outcome_minutes: 0,
      mfe_pct: 0,
      mae_pct: 0,
      plan_adherence_flags: { entry_in_zone: false, size_defined: true, target_reached: false, stop_respected: true },
      realized_pnl_pct: 0,
    },
    execution_realism: btcExecutionRealism,
    execution_quality: btcExecutionQuality,
    adherence: btcProposedAdherence,
    review_due: false,
    data_reality: btcDataReality,
  },
];

export const mockPaperTradesActive: PaperTradeView[] = [
  {
    trade_id: "paper_trade_open_eth",
    signal_id: mockSignals[1].signal_id,
    risk_report_id: mockRisk[1].risk_report_id,
    strategy_id: "event_continuation_v1",
    symbol: "ETH",
    side: "long",
    proposed_entry_zone: { low: 3555, high: 3610 },
    actual_entry: 3595,
    stop: 3440,
    targets: { base: 3745, stretch: 3810 },
    size_plan: { size_band: "small", max_portfolio_risk_pct: 0.4 },
    actual_size: 1.2,
    status: "opened",
    opened_at: "2026-03-12T10:30:00Z",
    closed_at: null,
    close_reason: "",
    close_price: null,
    notes: "Event-sensitive continuation probe remains open into macro follow-through.",
    freshness_minutes: 2880,
    data_quality: "paper",
    lifecycle_events: [
      { status: "proposed", note: "Proposed from event continuation signal.", timestamp: "2026-03-12T09:45:00Z" },
      { status: "opened", note: "Opened with reduced size because event risk remained elevated.", timestamp: "2026-03-12T10:30:00Z" },
    ],
    outcome: {
      entry_quality_label: "inside_zone",
      entry_zone_delta_pct: 0.35,
      stop_adherence: true,
      target_attainment: "none",
      time_to_outcome_minutes: 4380,
      mfe_pct: 1.25,
      mae_pct: -1.95,
      plan_adherence_flags: { entry_in_zone: true, size_defined: true, target_reached: false, stop_respected: true },
      realized_pnl_pct: -0.81,
    },
    execution_realism: ethExecutionRealism,
    execution_quality: ethExecutionQuality,
    adherence: ethOpenAdherence,
    review_due: false,
    data_reality: ethDataReality,
  },
];

export const mockPaperTradesClosed: PaperTradeView[] = [
  {
    trade_id: "paper_trade_closed_btc",
    signal_id: mockSignals[0].signal_id,
    risk_report_id: mockRisk[0].risk_report_id,
    strategy_id: "trend_breakout_v1",
    symbol: "BTC",
    side: "long",
    proposed_entry_zone: { low: 70480, high: 70980 },
    actual_entry: 70620,
    stop: 68450,
    targets: { base: 73120, stretch: 74840 },
    size_plan: { size_band: "medium", max_portfolio_risk_pct: 0.7 },
    actual_size: 0,
    status: "closed_win",
    opened_at: "2026-03-11T10:30:00Z",
    closed_at: "2026-03-12T14:00:00Z",
    close_reason: "target_hit",
    close_price: 73150,
    notes: "Base target filled after orderly follow-through.",
    freshness_minutes: 4260,
    data_quality: "paper",
    lifecycle_events: [
      { status: "proposed", note: "Proposed from BTC signal.", timestamp: "2026-03-11T09:55:00Z" },
      { status: "opened", note: "Opened after intraday reclaim.", timestamp: "2026-03-11T10:30:00Z" },
      { status: "closed_win", note: "Closed at base target.", timestamp: "2026-03-12T14:00:00Z" },
    ],
    outcome: {
      entry_quality_label: "inside_zone",
      entry_zone_delta_pct: 0.2,
      stop_adherence: true,
      target_attainment: "base",
      time_to_outcome_minutes: 1650,
      mfe_pct: 3.9,
      mae_pct: -0.82,
      plan_adherence_flags: { entry_in_zone: true, size_defined: true, target_reached: true, stop_respected: true },
      realized_pnl_pct: 3.58,
    },
    execution_realism: btcExecutionRealism,
    execution_quality: btcExecutionQuality,
    adherence: btcClosedAdherence,
    review_due: false,
    data_reality: btcDataReality,
  },
  {
    trade_id: "paper_trade_invalidated_eth",
    signal_id: mockSignals[1].signal_id,
    risk_report_id: mockRisk[1].risk_report_id,
    strategy_id: "vol_expansion_v1",
    symbol: "ETH",
    side: "long",
    proposed_entry_zone: { low: 3560, high: 3605 },
    actual_entry: 3582,
    stop: 3440,
    targets: { base: 3745, stretch: 3810 },
    size_plan: { size_band: "small", max_portfolio_risk_pct: 0.4 },
    actual_size: 0,
    status: "invalidated",
    opened_at: "2026-03-10T13:00:00Z",
    closed_at: "2026-03-10T18:00:00Z",
    close_reason: "invalidated",
    close_price: 3440,
    notes: "Macro release reversed the setup and invalidation was hit.",
    freshness_minutes: 6780,
    data_quality: "paper",
    lifecycle_events: [
      { status: "proposed", note: "Proposed from ETH event-sensitive setup.", timestamp: "2026-03-10T12:30:00Z" },
      { status: "opened", note: "Opened before the release window.", timestamp: "2026-03-10T13:00:00Z" },
      { status: "invalidated", note: "Exited at invalidation after macro reversal.", timestamp: "2026-03-10T18:00:00Z" },
    ],
    outcome: {
      entry_quality_label: "inside_zone",
      entry_zone_delta_pct: -0.01,
      stop_adherence: true,
      target_attainment: "none",
      time_to_outcome_minutes: 300,
      mfe_pct: 0.45,
      mae_pct: -4.02,
      plan_adherence_flags: { entry_in_zone: true, size_defined: true, target_reached: false, stop_respected: true },
      realized_pnl_pct: -3.96,
    },
    execution_realism: ethExecutionRealism,
    execution_quality: ethExecutionQuality,
    adherence: ethInvalidatedAdherence,
    review_due: false,
    data_reality: ethDataReality,
  },
];

export const mockPaperTradeReviews: PaperTradeReviewView[] = [
  {
    review_id: "paper_review_closed_btc",
    trade_id: "paper_trade_closed_btc",
    thesis_respected: true,
    invalidation_respected: true,
    entered_inside_suggested_zone: true,
    time_stop_respected: null,
    entered_too_early: false,
    entered_too_late: false,
    oversized: false,
    undersized: false,
    realism_warning_ignored: false,
    size_plan_respected: true,
    exited_per_plan: true,
    catalyst_mattered: true,
    failure_category: "",
    failure_categories: [],
    operator_notes: "Execution stayed inside the planned zone and the base target exit respected the original thesis.",
    updated_at: "2026-03-12T16:00:00Z",
  },
  {
    review_id: "paper_review_invalidated_eth",
    trade_id: "paper_trade_invalidated_eth",
    thesis_respected: false,
    invalidation_respected: false,
    entered_inside_suggested_zone: true,
    time_stop_respected: null,
    entered_too_early: true,
    entered_too_late: false,
    oversized: true,
    undersized: false,
    realism_warning_ignored: true,
    size_plan_respected: false,
    exited_per_plan: false,
    catalyst_mattered: true,
    failure_category: "operator_timing",
    failure_categories: ["operator_timing", "realism_ignored", "execution_plan_violation"],
    operator_notes: "The setup was entered before the release cleared and the realism warning was ignored.",
    updated_at: "2026-03-10T19:00:00Z",
  },
];

export const mockPaperTradeDetail: PaperTradeDetailView = {
  ...mockPaperTradesClosed[0],
  linked_signal: mockSignals[0],
  linked_risk: mockRisk[0],
  review: mockPaperTradeReviews[0],
  timeline: btcTimeline,
  scenario_stress: btcScenarioStress,
};

export const mockBrokerSnapshot: BrokerAdapterSnapshotView = {
  generated_at: "2026-03-15T11:30:00Z",
  balances: [
    {
      venue: "mock_broker",
      account_label: "shadow_book",
      asset: "USD",
      free: 25000,
      locked: 0,
      usd_value: 25000,
      source_type: "fixture",
    },
    {
      venue: "mock_broker",
      account_label: "shadow_book",
      asset: "BTC",
      free: 0.18,
      locked: 0,
      usd_value: 12960,
      source_type: "fixture",
    },
  ],
  positions: [
    {
      venue: "mock_broker",
      symbol: "BTC",
      side: "long",
      size: 0.18,
      entry_price: 70120,
      mark_price: 71880,
      unrealized_pnl_pct: 2.51,
      source_type: "fixture",
    },
  ],
  fill_imports: [
    {
      venue: "mock_broker",
      import_batch_id: "import_shadow_001",
      fill_count: 1,
      latest_fill_at: "2026-03-15T11:30:00Z",
      notes: "Fixture-safe imported fill batch for reconciliation testing.",
      source_type: "fixture",
    },
  ],
};

export const mockManualFill: ManualFillView = {
  fill_id: "fill_btc_manual_001",
  ticket_id: "ticket_btc_manual",
  trade_id: mockPaperTradesActive[0].trade_id,
  source: "manual_import",
  symbol: "BTC",
  side: "long",
  filled_at: "2026-03-15T11:30:00Z",
  fill_price: 71910,
  fill_size: 0.5,
  fees: 12.5,
  slippage_bps: 4.17,
  notes: "Fixture manual fill imported for reconciliation.",
  import_batch_id: "import_shadow_001",
  reconciliation: {
    planned_entry_reference: 71880,
    actual_fill_price: 71910,
    actual_slippage_bps: 4.17,
    modeled_slippage_bps: 7.5,
    slippage_variance_bps: -3.33,
    entered_inside_zone: true,
    requires_review: false,
    summary: "Actual fill 71910.00 versus planned 71880.00; variance -3.33bps against modeled slippage.",
  },
};

export const mockTicketList: TradeTicketView[] = [
  {
    ticket_id: "ticket_btc_review",
    signal_id: mockSignals[0].signal_id,
    risk_report_id: mockRisk[0].risk_report_id,
    trade_id: null,
    strategy_id: "trend_breakout_v1",
    symbol: "BTC",
    side: "long",
    proposed_entry_zone: { low: 71664.36, high: 72095.64 },
    planned_stop: 68450,
    planned_targets: mockSignals[0].targets,
    planned_size: { size_band: "medium", target_units: 0.5, max_risk_pct: 0.7 },
    realism_summary: { realism_score: 48, realism_grade: "B", source_type: "fixture", source_timing: "fixture", warning: btcDataReality.ui_warning, alignment_note: btcDataReality.tradable_alignment_note, modeled_slippage_bps: 7.5 },
    freshness_summary: { freshness_minutes: 5, freshness_state: "fresh", signal_freshness_minutes: 5, risk_freshness_minutes: 5 },
    checklist_status: {
      freshness_acceptable: true,
      realism_acceptable: true,
      risk_budget_available: true,
      cluster_exposure_acceptable: true,
      review_complete: true,
      operator_acknowledged: true,
      completed: true,
      blocked_reasons: [],
    },
    approval_status: "pending",
    status: "ready_for_review",
    shadow_status: "pending",
    created_at: "2026-03-15T11:30:00Z",
    expires_at: "2026-03-15T17:30:00Z",
    notes: "Primary BTC ticket awaiting operator approval.",
    freshness_minutes: 5,
    linked_signal_family: "trend_breakout",
    data_reality: btcDataReality,
  },
  {
    ticket_id: "ticket_eth_shadow",
    signal_id: mockSignals[1].signal_id,
    risk_report_id: mockRisk[1].risk_report_id,
    trade_id: mockPaperTradesClosed[0].trade_id,
    strategy_id: "event_continuation_v1",
    symbol: "ETH",
    side: "long",
    proposed_entry_zone: { low: 3577.236, high: 3598.764 },
    planned_stop: 3440,
    planned_targets: mockSignals[1].targets,
    planned_size: { size_band: "small", target_units: 0.25, max_risk_pct: 0.4 },
    realism_summary: { realism_score: 42, realism_grade: "B", source_type: "fixture", source_timing: "fixture", warning: ethDataReality.ui_warning, alignment_note: ethDataReality.tradable_alignment_note, modeled_slippage_bps: 12.5 },
    freshness_summary: { freshness_minutes: 5, freshness_state: "fresh", signal_freshness_minutes: 5, risk_freshness_minutes: 5 },
    checklist_status: {
      freshness_acceptable: true,
      realism_acceptable: true,
      risk_budget_available: true,
      cluster_exposure_acceptable: true,
      review_complete: true,
      operator_acknowledged: true,
      completed: true,
      blocked_reasons: [],
    },
    approval_status: "approved",
    status: "shadow_active",
    shadow_status: "monitoring",
    created_at: "2026-03-15T11:30:00Z",
    expires_at: "2026-03-15T15:30:00Z",
    notes: "Shadow-mode monitoring ticket for event-sensitive ETH context.",
    freshness_minutes: 5,
    linked_signal_family: "event_driven",
    data_reality: ethDataReality,
  },
  {
    ticket_id: "ticket_btc_manual",
    signal_id: mockSignals[0].signal_id,
    risk_report_id: mockRisk[0].risk_report_id,
    trade_id: mockPaperTradesActive[0].trade_id,
    strategy_id: "trend_breakout_v1",
    symbol: "BTC",
    side: "long",
    proposed_entry_zone: { low: 71664.36, high: 72095.64 },
    planned_stop: 68450,
    planned_targets: mockSignals[0].targets,
    planned_size: { size_band: "medium", target_units: 0.5, max_risk_pct: 0.7 },
    realism_summary: { realism_score: 48, realism_grade: "B", source_type: "fixture", source_timing: "fixture", warning: btcDataReality.ui_warning, alignment_note: btcDataReality.tradable_alignment_note, modeled_slippage_bps: 7.5 },
    freshness_summary: { freshness_minutes: 5, freshness_state: "fresh", signal_freshness_minutes: 5, risk_freshness_minutes: 5 },
    checklist_status: {
      freshness_acceptable: true,
      realism_acceptable: true,
      risk_budget_available: true,
      cluster_exposure_acceptable: true,
      review_complete: true,
      operator_acknowledged: true,
      completed: true,
      blocked_reasons: [],
    },
    approval_status: "approved",
    status: "manually_executed",
    shadow_status: "pending",
    created_at: "2026-03-15T11:30:00Z",
    expires_at: "2026-03-15T23:30:00Z",
    notes: "Manual external execution captured for reconciliation review.",
    freshness_minutes: 5,
    linked_signal_family: "trend_breakout",
    data_reality: btcDataReality,
  },
];

export const mockTicketDetail: TradeTicketDetailView = {
  ...mockTicketList[2],
  linked_signal: mockSignalDetail,
  linked_risk: mockRiskDetail,
  linked_trade: mockPaperTradeDetail,
  shadow_summary: {
    observed_at: "2026-03-15T11:30:00Z",
    observed_price: 71880,
    planned_reference_price: 71880,
    observed_vs_plan_pct: 0,
    ticket_valid: true,
    divergence_flag: false,
    divergence_reason: "",
    market_path_note: "Observed BTC at 71880.00 versus planned reference 71880.00.",
    freshness_state: "fresh",
  },
  manual_fills: [mockManualFill],
  broker_snapshot: mockBrokerSnapshot,
};

export const mockShadowTickets: TradeTicketDetailView[] = [
  {
    ...mockTicketList[1],
    linked_signal: { ...mockSignalDetail, ...mockSignals[1] },
    linked_risk: { ...mockRiskDetail, ...mockRisk[1], linked_signal: mockSignals[1] },
    linked_trade: mockPaperTradeDetail,
    shadow_summary: {
      observed_at: "2026-03-15T11:30:00Z",
      observed_price: 3588,
      planned_reference_price: 3588,
      observed_vs_plan_pct: 0,
      ticket_valid: true,
      divergence_flag: false,
      divergence_reason: "",
      market_path_note: "Observed ETH at 3588.00 versus planned reference 3588.00. Event-driven tickets carry extra path uncertainty.",
      freshness_state: "fresh",
    },
    manual_fills: [],
    broker_snapshot: mockBrokerSnapshot,
  },
  mockTicketDetail,
];

export const mockReplay = {
  generated_at: "2026-03-15T11:30:00Z",
  symbol: "BTC",
  signal_id: mockSignals[0].signal_id,
  trade_id: mockPaperTradeDetail.trade_id,
  event_window_minutes: 180,
  frames: [
    {
      cursor: "2026-03-15T08:30:00Z",
      bars: mockBars.BTC.slice(0, 2),
      signals: [],
      risks: [],
      alerts: [],
      paper_trades: [],
    },
    {
      cursor: "2026-03-15T11:30:00Z",
      bars: mockBars.BTC,
      signals: [mockSignals[0]],
      risks: [mockRisk[0]],
      alerts: [
        {
          alert_id: "alert_1",
          created_at: "2026-03-15T11:25:00Z",
          signal_id: mockSignals[0].signal_id,
          risk_report_id: mockRisk[0].risk_report_id,
          asset_ids: ["BTC", "ETH"],
          severity: "info",
          category: "signal_ranked",
          channel_targets: ["in_app", "discord"],
          title: "BTC signal created",
          body: "Breakout above the 20-day range remains intact with aligned structure and supportive volume.",
          tags: ["trend_breakout", "long", "BTC"],
          dedupe_key: `signal_ranked:${mockSignals[0].signal_id}`,
          status: "sent",
          delivery_metadata: { sent_channels: ["in_app", "discord"], failed_channels: [] },
          data_quality: "fixture",
          suppressed_reason: null,
        },
      ],
      paper_trades: [mockPaperTradeDetail],
    },
    {
      cursor: "2026-03-15T14:30:00Z",
      bars: mockBars.BTC.slice(1),
      signals: [mockSignals[0]],
      risks: [mockRisk[0]],
      alerts: [
        {
          alert_id: "alert_1",
          created_at: "2026-03-15T11:25:00Z",
          signal_id: mockSignals[0].signal_id,
          risk_report_id: mockRisk[0].risk_report_id,
          asset_ids: ["BTC", "ETH"],
          severity: "info",
          category: "signal_ranked",
          channel_targets: ["in_app", "discord"],
          title: "BTC signal created",
          body: "Breakout above the 20-day range remains intact with aligned structure and supportive volume.",
          tags: ["trend_breakout", "long", "BTC"],
          dedupe_key: `signal_ranked:${mockSignals[0].signal_id}`,
          status: "sent",
          delivery_metadata: { sent_channels: ["in_app", "discord"], failed_channels: [] },
          data_quality: "fixture",
          suppressed_reason: null,
        },
      ],
      paper_trades: [mockPaperTradeDetail],
    },
  ],
};

export const mockScenarioStressSummary = {
  generated_at: "2026-03-15T11:30:00Z",
  signal_impacts: [
    { scenario: "btc_down", entity_type: "signal", entity_id: mockSignals[0].signal_id, symbol: "BTC", severity: "critical", shock_pct: -8, pnl_impact_pct: -8, confidence_impact: 0.67, rationale: "BTC signal stress uses deterministic btc_down shock with score 74.6." },
    { scenario: "yield_shock", entity_type: "signal", entity_id: mockSignals[0].signal_id, symbol: "BTC", severity: "warning", shock_pct: -3.9, pnl_impact_pct: -3.9, confidence_impact: 0.33, rationale: "BTC signal stress uses deterministic yield_shock shock with score 74.6." },
  ],
  active_trade_impacts: btcScenarioStress,
  promoted_strategy_impacts: [
    { scenario: "btc_down", entity_type: "strategy", entity_id: "trend_breakout_v1", symbol: "BTC", severity: "critical", shock_pct: -8, pnl_impact_pct: -6.4, confidence_impact: 0.57, rationale: "Promoted strategy trend_breakout_v1 inherits deterministic btc_down stress from BTC." },
  ],
};

export const mockPaperTradeAnalytics: PaperTradeAnalyticsView = {
  generated_at: "2026-03-15T11:30:00Z",
  by_signal_family: [
    {
      grouping: "signal_family",
      key: "trend_breakout",
      trade_count: 1,
      hit_rate: 1,
      expectancy_proxy: 3.58,
      target_attainment_rate: 1,
      invalidation_rate: 0,
      avg_entry_zone_delta_pct: 0.2,
      avg_mfe_pct: 3.9,
      avg_mae_pct: -0.82,
    },
    {
      grouping: "signal_family",
      key: "event_driven",
      trade_count: 1,
      hit_rate: 0,
      expectancy_proxy: -3.96,
      target_attainment_rate: 0,
      invalidation_rate: 1,
      avg_entry_zone_delta_pct: -0.01,
      avg_mfe_pct: 0.45,
      avg_mae_pct: -4.02,
    },
  ],
  by_asset_class: [
    {
      grouping: "asset_class",
      key: "crypto",
      trade_count: 2,
      hit_rate: 0.5,
      expectancy_proxy: -0.19,
      target_attainment_rate: 0.5,
      invalidation_rate: 0.5,
      avg_entry_zone_delta_pct: 0.1,
      avg_mfe_pct: 2.18,
      avg_mae_pct: -2.42,
    },
  ],
  by_strategy: [
    {
      grouping: "strategy",
      key: "trend_breakout_v1",
      trade_count: 1,
      hit_rate: 1,
      expectancy_proxy: 3.58,
      target_attainment_rate: 1,
      invalidation_rate: 0,
      avg_entry_zone_delta_pct: 0.2,
      avg_mfe_pct: 3.9,
      avg_mae_pct: -0.82,
    },
    {
      grouping: "strategy",
      key: "vol_expansion_v1",
      trade_count: 1,
      hit_rate: 0,
      expectancy_proxy: -3.96,
      target_attainment_rate: 0,
      invalidation_rate: 1,
      avg_entry_zone_delta_pct: -0.01,
      avg_mfe_pct: 0.45,
      avg_mae_pct: -4.02,
    },
  ],
  by_strategy_lifecycle_state: [
    {
      grouping: "strategy_lifecycle_state",
      key: "promoted",
      trade_count: 1,
      hit_rate: 1,
      expectancy_proxy: 3.58,
      target_attainment_rate: 1,
      invalidation_rate: 0,
      avg_entry_zone_delta_pct: 0.2,
      avg_mfe_pct: 3.9,
      avg_mae_pct: -0.82,
    },
    {
      grouping: "strategy_lifecycle_state",
      key: "experimental",
      trade_count: 1,
      hit_rate: 0,
      expectancy_proxy: -3.96,
      target_attainment_rate: 0,
      invalidation_rate: 1,
      avg_entry_zone_delta_pct: -0.01,
      avg_mfe_pct: 0.45,
      avg_mae_pct: -4.02,
    },
  ],
  by_score_bucket: [
    {
      grouping: "score_bucket",
      key: "low",
      trade_count: 1,
      hit_rate: 0,
      expectancy_proxy: -3.96,
      target_attainment_rate: 0,
      invalidation_rate: 1,
      avg_entry_zone_delta_pct: -0.01,
      avg_mfe_pct: 0.45,
      avg_mae_pct: -4.02,
    },
    {
      grouping: "score_bucket",
      key: "top",
      trade_count: 1,
      hit_rate: 1,
      expectancy_proxy: 3.58,
      target_attainment_rate: 1,
      invalidation_rate: 0,
      avg_entry_zone_delta_pct: 0.2,
      avg_mfe_pct: 3.9,
      avg_mae_pct: -0.82,
    },
  ],
  by_realism_bucket: [
    {
      grouping: "realism_bucket",
      key: "strong",
      trade_count: 1,
      hit_rate: 1,
      expectancy_proxy: 3.58,
      target_attainment_rate: 1,
      invalidation_rate: 0,
      avg_entry_zone_delta_pct: 0.2,
      avg_mfe_pct: 3.9,
      avg_mae_pct: -0.82,
    },
    {
      grouping: "realism_bucket",
      key: "usable",
      trade_count: 1,
      hit_rate: 0,
      expectancy_proxy: -3.96,
      target_attainment_rate: 0,
      invalidation_rate: 1,
      avg_entry_zone_delta_pct: -0.01,
      avg_mfe_pct: 0.45,
      avg_mae_pct: -4.02,
    },
  ],
  by_realism_grade: [
    {
      grouping: "realism_grade",
      key: "B",
      trade_count: 2,
      hit_rate: 0.5,
      expectancy_proxy: -0.19,
      target_attainment_rate: 0.5,
      invalidation_rate: 0.5,
      avg_entry_zone_delta_pct: 0.1,
      avg_mfe_pct: 2.18,
      avg_mae_pct: -2.42,
    },
  ],
  by_freshness_state: [
    {
      grouping: "freshness_state",
      key: "fresh",
      trade_count: 2,
      hit_rate: 0.5,
      expectancy_proxy: -0.19,
      target_attainment_rate: 0.5,
      invalidation_rate: 0.5,
      avg_entry_zone_delta_pct: 0.1,
      avg_mfe_pct: 2.18,
      avg_mae_pct: -2.42,
    },
  ],
  by_asset: [
    {
      grouping: "asset",
      key: "BTC",
      trade_count: 1,
      hit_rate: 1,
      expectancy_proxy: 3.58,
      target_attainment_rate: 1,
      invalidation_rate: 0,
      avg_entry_zone_delta_pct: 0.2,
      avg_mfe_pct: 3.9,
      avg_mae_pct: -0.82,
    },
    {
      grouping: "asset",
      key: "ETH",
      trade_count: 1,
      hit_rate: 0,
      expectancy_proxy: -3.96,
      target_attainment_rate: 0,
      invalidation_rate: 1,
      avg_entry_zone_delta_pct: -0.01,
      avg_mfe_pct: 0.45,
      avg_mae_pct: -4.02,
    },
  ],
  by_signal_quality: [
    {
      grouping: "signal_quality",
      key: "fragile",
      trade_count: 1,
      hit_rate: 0,
      expectancy_proxy: -3.96,
      target_attainment_rate: 0,
      invalidation_rate: 1,
      avg_entry_zone_delta_pct: -0.01,
      avg_mfe_pct: 0.45,
      avg_mae_pct: -4.02,
    },
    {
      grouping: "signal_quality",
      key: "strong",
      trade_count: 1,
      hit_rate: 1,
      expectancy_proxy: 3.58,
      target_attainment_rate: 1,
      invalidation_rate: 0,
      avg_entry_zone_delta_pct: 0.2,
      avg_mfe_pct: 3.9,
      avg_mae_pct: -0.82,
    },
  ],
  by_plan_quality: [
    {
      grouping: "plan_quality",
      key: "context_limited",
      trade_count: 2,
      hit_rate: 0.5,
      expectancy_proxy: -0.19,
      target_attainment_rate: 0.5,
      invalidation_rate: 0.5,
      avg_entry_zone_delta_pct: 0.1,
      avg_mfe_pct: 2.18,
      avg_mae_pct: -2.42,
    },
  ],
  by_execution_quality: [
    {
      grouping: "execution_quality",
      key: "clean",
      trade_count: 1,
      hit_rate: 1,
      expectancy_proxy: 3.58,
      target_attainment_rate: 1,
      invalidation_rate: 0,
      avg_entry_zone_delta_pct: 0.2,
      avg_mfe_pct: 3.9,
      avg_mae_pct: -0.82,
    },
    {
      grouping: "execution_quality",
      key: "penalized",
      trade_count: 1,
      hit_rate: 0,
      expectancy_proxy: -3.96,
      target_attainment_rate: 0,
      invalidation_rate: 1,
      avg_entry_zone_delta_pct: -0.01,
      avg_mfe_pct: 0.45,
      avg_mae_pct: -4.02,
    },
  ],
  hygiene_summary: {
    trade_count: 2,
    reviewed_trade_count: 2,
    adherence_rate: 0.63,
    invalidation_discipline_rate: 0.5,
    realism_warning_violation_rate: 0.5,
    review_completion_rate: 1,
    poor_adherence_streak: 1,
    review_backlog: 0,
    realism_warning_violation_count: 1,
    invalidation_breach_count: 1,
    promoted_strategy_drift_count: 0,
    promoted_strategy_drift: [],
  },
  failure_categories: [
    { category: "operator_timing", trade_count: 1, operator_error: true },
    { category: "execution_plan_violation", trade_count: 1, operator_error: true },
    { category: "realism_ignored", trade_count: 1, operator_error: true },
  ],
};

export const mockWalletBalances: WalletBalanceView[] = [
  {
    venue: "paper",
    account_label: "Research Book",
    updated_at: "2026-03-15T09:15:00Z",
    total_usd: 125640,
    available_usd: 81420,
    data_quality: "fixture",
    balances: [
      { asset: "USD", free: 81420, locked: 0, usd_value: 81420 },
      { asset: "BTC", free: 0.42, locked: 0, usd_value: 30190 },
      { asset: "ETH", free: 3.9, locked: 0.6, usd_value: 14030 },
    ],
  },
];

export const mockJournal: JournalReviewView[] = [
  {
    journal_id: "journal_932840b8f8e95d8fa3c71ecf12ef7382",
    symbol: "BTC",
    entered_at: "2026-03-11T15:00:00Z",
    entry_type: "review",
    note: "Trend quality improved after reclaiming the 20-day breakout level, but CPI kept conviction moderate.",
    mood: "disciplined",
    tags: ["trend", "macro", "btc"],
    signal_id: mockSignals[0].signal_id,
    risk_report_id: mockRisk[0].risk_report_id,
    trade_id: mockActiveTrades[0].trade_id,
    setup_quality: 4,
    execution_quality: 4,
    follow_through: "held core and respected event-risk trim plan",
    outcome: "open",
    lessons: "Cap size to medium when a high-impact macro release is inside 24h.",
    review_status: "in_review",
    updated_at: "2026-03-15T11:20:00Z",
    freshness_minutes: 10,
  },
];

export const mockAlerts: AlertEnvelope[] = [
  {
    alert_id: "alert_1",
    created_at: "2026-03-15T11:25:00Z",
    signal_id: mockSignals[0].signal_id,
    risk_report_id: mockRisk[0].risk_report_id,
    asset_ids: ["BTC", "ETH"],
    severity: "info",
    category: "signal_ranked",
    channel_targets: ["in_app", "discord"],
    title: "BTC signal created",
    body: "Breakout above the 20-day range remains intact with aligned structure and supportive volume.",
    tags: ["trend_breakout", "long", "BTC"],
    dedupe_key: `signal_ranked:${mockSignals[0].signal_id}`,
    status: "sent",
    delivery_metadata: { sent_channels: ["in_app", "discord"], failed_channels: [] },
    data_quality: "fixture",
    suppressed_reason: null,
  },
  {
    alert_id: "alert_2",
    created_at: "2026-03-15T11:25:00Z",
    signal_id: mockSignals[1].signal_id,
    risk_report_id: mockRisk[1].risk_report_id,
    asset_ids: ["ETH", "BTC"],
    severity: "warning",
    category: "high_risk_signal",
    channel_targets: ["in_app", "telegram", "discord"],
    title: "ETH marked high risk",
    body: "Noise 41% with uncertainty 0.42.",
    tags: ["high-risk", "event_driven", "ETH"],
    dedupe_key: `high_risk_signal:${mockSignals[1].signal_id}`,
    status: "failed",
    delivery_metadata: { sent_channels: ["in_app"], failed_channels: ["telegram", "discord"] },
    data_quality: "fixture",
    suppressed_reason: null,
  },
  {
    alert_id: "alert_3",
    created_at: "2026-03-15T11:30:00Z",
    signal_id: null,
    risk_report_id: null,
    asset_ids: [],
    severity: "info",
    category: "daily_digest_summary",
    channel_targets: ["in_app"],
    title: "Daily operator digest",
    body: "Signals 2, focus queue 1, risk budget 1.100/2.500. Lead signal: BTC trend_breakout score 74.6.",
    tags: ["daily-digest", "sample"],
    dedupe_key: "daily_digest:2026-03-15",
    status: "suppressed",
    delivery_metadata: { suppressed_by: "alert_1", reason: "dedupe_window" },
    data_quality: "fixture",
    suppressed_reason: "dedupe_window",
  },
  {
    alert_id: "alert_4",
    created_at: "2026-03-15T11:30:00Z",
    signal_id: mockSignals[1].signal_id,
    risk_report_id: mockRisk[1].risk_report_id,
    asset_ids: ["ETH"],
    severity: "warning",
    category: "paper_trade_review_due",
    channel_targets: ["in_app"],
    title: "ETH review due",
    body: "Closed paper trade paper_trade_invalidated_eth is awaiting structured review.",
    tags: ["ETH", "invalidated", "paper_trade_review_due"],
    dedupe_key: "paper_trade_review_due:paper_trade_invalidated_eth:invalidated",
    status: "sent",
    delivery_metadata: { sent_channels: ["in_app"], failed_channels: [] },
    data_quality: "paper",
    suppressed_reason: null,
  },
];

const mockStrategyDriftWarnings: StrategyDriftWarningView[] = [
  {
    strategy_name: "trend_breakout_v1",
    lifecycle_state: "promoted",
    drift_indicator: "stable",
    note: "No promoted strategy drift flags in the current fixture cohort.",
  },
];

const mockDegradedSources: DegradedSourceView[] = [
  {
    symbol: "WTI",
    source_type: "proxy",
    source_timing: "end_of_day",
    freshness_state: "fresh",
    realism_grade: "E",
    warning:
      "WTI research uses contextual proxy bars and should not be treated like direct CL futures pricing.",
  },
];

export const mockReviewTasks: ReviewTaskView[] = [
  {
    task_id: "review_task_open_btc",
    task_type: "open_trade_checkin",
    title: "BTC open trade check-in",
    summary: "Open trade has aged into a required operator check-in.",
    state: "open",
    priority: "medium",
    session_state: "live_session",
    linked_entity_type: "paper_trade",
    linked_entity_id: mockPaperTradesActive[0].trade_id,
    linked_symbol: "BTC",
    signal_id: mockSignals[0].signal_id,
    risk_report_id: mockRisk[0].risk_report_id,
    trade_id: mockPaperTradesActive[0].trade_id,
    strategy_name: "trend_breakout_v1",
    due_at: "2026-03-15T15:30:00Z",
    created_at: "2026-03-15T11:30:00Z",
    updated_at: "2026-03-15T11:30:00Z",
    completed_at: null,
    freshness_minutes: 0,
    overdue: false,
    notes: "",
    metadata: { status: "opened", freshness_minutes: 120 },
  },
  {
    task_id: "review_task_post_eth",
    task_type: "post_trade_review_due",
    title: "ETH post-trade review due",
    summary: "Closed paper trade is awaiting structured review.",
    state: "overdue",
    priority: "high",
    session_state: "post_session",
    linked_entity_type: "paper_trade_review",
    linked_entity_id: "paper_trade_invalidated_eth",
    linked_symbol: "ETH",
    signal_id: mockSignals[1].signal_id,
    risk_report_id: mockRisk[1].risk_report_id,
    trade_id: "paper_trade_invalidated_eth",
    strategy_name: "vol_expansion_v1",
    due_at: "2026-03-12T18:00:00Z",
    created_at: "2026-03-12T18:00:00Z",
    updated_at: "2026-03-15T11:30:00Z",
    completed_at: null,
    freshness_minutes: 0,
    overdue: true,
    notes: "",
    metadata: { close_reason: "invalidated" },
  },
];

export const mockDailyBriefing: DailyBriefingView = {
  generated_at: "2026-03-15T11:30:00Z",
  top_ranked_signals: mockSignals,
  high_risk_setups: mockHighRiskSignals,
  open_trades_needing_attention: [
    {
      trade_id: mockPaperTradesActive[0].trade_id,
      symbol: "BTC",
      status: "opened",
      attention_reason: "Active paper trade requires monitoring.",
      freshness_minutes: mockPaperTradesActive[0].freshness_minutes,
      signal_id: mockSignals[0].signal_id,
      risk_report_id: mockRisk[0].risk_report_id,
    },
  ],
  exposure_summary: mockRiskExposure,
  degraded_data_sources: mockDegradedSources,
  scout_to_focus_promotions: mockOpportunities.focus_queue,
  promoted_strategy_drift_warnings: mockStrategyDriftWarnings,
};

export const mockWeeklyReview: WeeklyReviewView = {
  generated_at: "2026-03-15T11:30:00Z",
  signal_family_outcomes: mockPaperTradeAnalytics.by_signal_family,
  adherence_trend: mockPaperTradeAnalytics.hygiene_summary,
  failure_attribution_trend: mockPaperTradeAnalytics.failure_categories,
  realism_warning_violations: mockPaperTradeReviews.filter((row) => row.realism_warning_ignored),
  strategy_promotion_health: mockStrategyDriftWarnings,
  paper_trade_outcome_distribution: {
    wins: 1,
    losses: 0,
    invalidated: 1,
    timed_out: 0,
    cancelled: 0,
  },
};

export const mockOperationalBacklog: OperationalBacklogView = {
  generated_at: "2026-03-15T11:30:00Z",
  overdue_count: 1,
  high_priority_count: 1,
  items: [
    {
      item_id: "backlog_post_trade_review_eth",
      category: "post_trade_review_due",
      title: "ETH post-trade review due",
      priority: "high",
      status: "overdue",
      linked_symbol: "ETH",
      linked_entity_type: "paper_trade_review",
      linked_entity_id: "paper_trade_invalidated_eth",
      due_at: "2026-03-12T18:00:00Z",
      freshness_minutes: 0,
      note: "Closed paper trade is awaiting structured review.",
    },
  ],
};

export const mockSessionOverview: SessionOverviewView = {
  generated_at: "2026-03-15T11:30:00Z",
  states: [
    {
      state: "pre_session",
      title: "Pre Session",
      headline: "1 active items",
      summary: "1 high-priority tasks and 0 overdue items.",
      item_count: 1,
      overdue_count: 0,
      high_priority_count: 1,
      freshness_status: "fresh",
    },
    {
      state: "live_session",
      title: "Live Session",
      headline: "1 active items",
      summary: "0 high-priority tasks and 0 overdue items.",
      item_count: 1,
      overdue_count: 0,
      high_priority_count: 0,
      freshness_status: "fresh",
    },
    {
      state: "post_session",
      title: "Post Session",
      headline: "1 active items",
      summary: "1 high-priority tasks and 1 overdue items.",
      item_count: 1,
      overdue_count: 1,
      high_priority_count: 1,
      freshness_status: "fresh",
    },
    {
      state: "weekly_review",
      title: "Weekly Review",
      headline: "1 active items",
      summary: "1 high-priority tasks and 1 overdue items.",
      item_count: 1,
      overdue_count: 1,
      high_priority_count: 1,
      freshness_status: "fresh",
    },
    {
      state: "strategy_review",
      title: "Strategy Review",
      headline: "0 active items",
      summary: "0 high-priority tasks and 0 overdue items.",
      item_count: 0,
      overdue_count: 0,
      high_priority_count: 0,
      freshness_status: "fresh",
    },
  ],
  review_tasks: mockReviewTasks,
  daily_briefing: mockDailyBriefing,
  weekly_review: mockWeeklyReview,
  operational_backlog: mockOperationalBacklog,
};

export const mockPilotMetrics: PilotMetricSummaryView = {
  generated_at: "2026-03-15T11:30:00Z",
  ticket_conversion: { created: 3, approved_rate: 0.67, shadow_rate: 0.33, manual_execution_rate: 0.33 },
  shadow_metrics: { divergence_rate: 0.0, divergence_count: 0, shadow_active_count: 1 },
  slippage_metrics: { avg_manual_slippage_variance_bps: 3.33, reconciliation_drift_count: 0, manual_fill_count: 1 },
  alert_metrics: { actionable_alert_count: 12, ignored_alert_rate: 0.08, delivery_issue_rate: 0.17 },
  adherence_metrics: { adherence_rate: 0.63, invalidation_discipline_rate: 0.5, realism_warning_violation_rate: 0.5 },
  review_backlog_metrics: { review_backlog: 0, overdue_backlog: 1, high_priority_backlog: 1 },
  promoted_strategy_metrics: { promoted_count: 1, degradation_rate: 0 },
  mismatch_causes: [{ cause: "no_material_mismatch", count: 1 }],
};

export const mockExecutionGate: ExecutionGateView = {
  status: "pilot_running",
  blockers: ["approved ticket conversion is below pilot threshold"],
  thresholds: {
    approved_rate_min: 0.3,
    shadow_divergence_rate_max: 0.4,
    avg_manual_slippage_variance_bps_max: 12,
    review_backlog_max: 2,
    promoted_degradation_rate_max: 0.4,
  },
  metrics: {
    approved_rate: 0.67,
    shadow_divergence_rate: 0,
    avg_manual_slippage_variance_bps: 3.33,
    review_backlog: 0,
    promoted_degradation_rate: 0,
  },
  rationale: [
    "Approved rate 0.67 against minimum 0.30.",
    "Shadow divergence 0.00 against max 0.40.",
  ],
};

export const mockAdapterHealth: AdapterHealthView[] = [
  {
    health_id: "adapter_health_mock_broker",
    adapter_name: "mock_broker",
    status: "healthy",
    checked_at: "2026-03-15T11:30:00Z",
    details: { balances: 2, positions: 1, fill_imports: 1, credentials_present: { telegram: false, discord: false }, read_only: true },
  },
];

export const mockAuditLogs: AuditLogView[] = [
  {
    audit_id: "audit_ticket_approval_001",
    created_at: "2026-03-15T11:30:00Z",
    event_type: "ticket_approval",
    entity_type: "trade_ticket",
    entity_id: "ticket_btc_manual",
    actor: "local_operator",
    details: { approval_status: "approved", status: "approved", notes: "Checklist completed." },
  },
  {
    audit_id: "audit_manual_fill_001",
    created_at: "2026-03-15T11:30:00Z",
    event_type: "manual_fill_entry",
    entity_type: "manual_fill",
    entity_id: "fill_btc_manual_001",
    actor: "local_operator",
    details: { ticket_id: "ticket_btc_manual", source: "manual_import", slippage_bps: 4.17 },
  },
];

export const mockPilotDashboard: PilotDashboardView = {
  generated_at: "2026-03-15T11:30:00Z",
  pilot_metrics: mockPilotMetrics,
  trust_by_asset_class: [
    { asset_class: "crypto", avg_realism_score: 45, count: 3 },
  ],
  divergence_hotspots: [],
  operator_discipline: {
    adherence_rate: 0.63,
    ignored_alert_rate: 0.08,
    review_completion_pressure: 0,
  },
  review_backlog: mockOperationalBacklog,
  execution_gate: mockExecutionGate,
  adapter_health: mockAdapterHealth,
  recent_audit_logs: mockAuditLogs,
};

export const mockDeskSummary: DeskSummaryView = {
  generated_at: "2026-03-15T11:30:00Z",
  session_states: mockSessionOverview.states,
  execution_gate: mockExecutionGate,
  operational_backlog: mockOperationalBacklog,
  review_tasks: mockReviewTasks,
  degraded_sources: mockDailyBriefing.degraded_data_sources,
  high_priority_signals: mockSignals,
  high_risk_signals: mockHighRiskSignals,
  focus_opportunities: mockOpportunities.focus_queue,
  open_tickets: mockTicketList,
  active_paper_trades: mockPaperTradesActive,
  shadow_divergence: [
    {
      ticket_id: "ticket_btc_manual",
      symbol: "BTC",
      reason: "no_material_mismatch",
      observed_vs_plan_pct: 0.18,
      freshness_state: "fresh",
    },
  ],
  adapter_health: mockAdapterHealth,
  audit_log_tail: mockAuditLogs,
};

export const mockHomeSummary: HomeOperatorSummaryView = {
  generated_at: "2026-03-15T11:30:00Z",
  session_states: mockSessionOverview.states,
  session_state: "post_session",
  pilot_gate_state: mockExecutionGate.status,
  degraded_source_count: mockDailyBriefing.degraded_data_sources.length,
  review_backlog_counts: {
    overdue: mockOperationalBacklog.overdue_count,
    high_priority: mockOperationalBacklog.high_priority_count,
    open_reviews: mockReviewTasks.length,
  },
  top_signals_summary: mockSignals,
  open_ticket_counts: {
    ready_for_review: 1,
    shadow_active: 1,
    manually_executed: 1,
  },
  active_trade_counts: {
    proposed: mockPaperTradesProposed.length,
    opened: mockPaperTradesActive.length,
    closed: mockPaperTradesClosed.length,
  },
  shadow_divergence_summary: {
    count: mockDeskSummary.shadow_divergence.length,
    max_observed_vs_plan_pct: 0.18,
  },
  adapter_health_summary: {
    healthy: 1,
  },
};

const mockOpsHistory: OpsActionView[] = [
  {
    action_id: "ops_refresh_001",
    action_name: "system_refresh",
    category: "safe_common",
    status: "success",
    started_at: "2026-03-15T11:25:00Z",
    finished_at: "2026-03-15T11:25:03Z",
    summary: "source_mode=sample | bars_ingested=1080 | signals_emitted=2 | risk_reports_built=2",
    log_path: "data/ops_logs/ops_refresh_001.log",
    details: { source_mode: "sample", bars_ingested: 1080, signals_emitted: 2, risk_reports_built: 2 },
  },
  {
    action_id: "ops_verify_fast_001",
    action_name: "verify_fast",
    category: "safe_common",
    status: "success",
    started_at: "2026-03-15T11:26:00Z",
    finished_at: "2026-03-15T11:26:18Z",
    summary: "backend tests passed | frontend tests passed | build passed",
    log_path: "data/ops_logs/ops_verify_fast_001.log",
    details: { backend: "passed", frontend: "passed", build: "passed" },
  },
  {
    action_id: "ops_export_001",
    action_name: "pilot_export",
    category: "safe_common",
    status: "success",
    started_at: "2026-03-15T11:27:00Z",
    finished_at: "2026-03-15T11:27:05Z",
    summary: "pilot_report_20260315_113000 exported",
    log_path: "data/ops_logs/ops_export_001.log",
    details: { report_path: "data/exports/pilot_report_20260315_113000" },
  },
  {
    action_id: "ops_bundle_001",
    action_name: "build_review_bundle",
    category: "heavy_maintenance",
    status: "success",
    started_at: "2026-03-15T11:28:00Z",
    finished_at: "2026-03-15T11:29:15Z",
    summary: "review_bundle.zip regenerated",
    log_path: "data/ops_logs/ops_bundle_001.log",
    details: { artifact: "review_bundle.zip" },
  },
];

export const mockOpsSummary: OpsSummaryView = {
  generated_at: "2026-03-15T11:30:00Z",
  latest_fast_verify: mockOpsHistory[1],
  latest_full_verify: null,
  latest_export: mockOpsHistory[2],
  latest_bundle: mockOpsHistory[3],
  latest_refresh: mockOpsHistory[0],
  latest_contract_snapshot: null,
  action_history: mockOpsHistory,
  available_actions: [
    { action_name: "system_refresh", label: "Refresh System", category: "safe_common", is_heavy: false, warning: "Refreshes the in-app pipeline state from fixture-safe sources." },
    { action_name: "fixture_refresh", label: "Refresh Fixture Data", category: "safe_common", is_heavy: false, warning: "Re-seeds deterministic fixture-mode data and refreshes derived views." },
    { action_name: "pilot_export", label: "Trigger Pilot Export", category: "safe_common", is_heavy: false, warning: "Writes a timestamped pilot report under data/exports." },
    { action_name: "save_contract_snapshots", label: "Save Contract Snapshots", category: "heavy_maintenance", is_heavy: true, warning: "Captures fixture-mode API contract snapshots for regression review." },
    { action_name: "build_review_bundle", label: "Build Review Bundle", category: "heavy_maintenance", is_heavy: true, warning: "Runs the compact review artifact builder and can take noticeable time." },
    { action_name: "verify_fast", label: "Run Fast Verify", category: "safe_common", is_heavy: false, warning: "Runs the fast local verification path." },
    { action_name: "verify_full", label: "Run Full Verify", category: "heavy_maintenance", is_heavy: true, warning: "Runs the full local verification chain and is slower." },
  ],
};

export const mockCommandCenter: CommandCenterStatusView = {
  generated_at: "2026-03-15T11:30:00Z",
  runtime_status: "fixture_mode",
  backend_health: "ok",
  frontend_runtime_status: "built",
  source_mode: "sample",
  pipeline_status: "completed",
  pipeline_freshness_minutes: 22,
  last_refresh: "2026-03-15T11:30:00Z",
  latest_export_path: "data/exports/pilot_report_20260315_113000",
  latest_export_generated_at: "2026-03-15T11:30:00Z",
  latest_review_bundle_path: "review_bundle.zip",
  latest_review_bundle_generated_at: "2026-03-15T11:30:00Z",
  frontend_build_generated_at: "2026-03-15T11:30:00Z",
  diagnostics_updated_at: "2026-03-15T11:30:00Z",
  verify_fast_available: true,
  verify_full_available: true,
  review_bundle_available: true,
  available_actions: mockOpsSummary.available_actions.map((item) => item.action_name),
  safe_actions: mockOpsSummary.available_actions.filter((item) => !item.is_heavy),
  heavy_actions: mockOpsSummary.available_actions.filter((item) => item.is_heavy),
  latest_fast_verify: mockOpsSummary.latest_fast_verify,
  latest_full_verify: mockOpsSummary.latest_full_verify,
  latest_export: mockOpsSummary.latest_export,
  latest_bundle: mockOpsSummary.latest_bundle,
  latest_refresh_action: mockOpsSummary.latest_refresh,
  latest_contract_snapshot: mockOpsSummary.latest_contract_snapshot,
  action_history: mockOpsSummary.action_history,
  notes: [
    "Safe operator actions only. No raw shell execution is exposed.",
    "Heavy actions require explicit confirmation in the UI before they run.",
    "Pilot export and contract snapshots reuse local fixture-safe reporting paths.",
  ],
};

export const mockPilotExportResponse: PilotExportResponse = {
  generated_at: "2026-03-15T11:30:00Z",
  report_path: "data/exports/pilot_report_20260315_113000",
  source_mode: "sample",
  pipeline_status: "completed",
};

export const mockSignalsSummary: SignalsSummaryView = {
  generated_at: "2026-03-15T11:30:00Z",
  filter_metadata: {
    symbols: ["BTC", "ETH"],
    families: ["event_driven", "trend_breakout"],
    directions: ["long", "neutral"],
    freshness_states: ["fresh"],
    realism_grades: ["B"],
  },
  grouped_counts: {
    family: { trend_breakout: 1, event_driven: 1 },
    direction: { long: 1, neutral: 1 },
    freshness: { fresh: 2 },
    realism: { B: 2 },
  },
  top_ranked_signals: mockSignals,
  warning_counts: {
    high_risk: 1,
    stale_or_degraded: 0,
    proxy_or_context_only: 0,
    promotion_blocked: 1,
  },
};

export const mockTicketSummary: TicketSummaryView = {
  generated_at: "2026-03-15T11:30:00Z",
  counts_by_state: { ready_for_review: 1, shadow_active: 1, manually_executed: 1 },
  checklist_blockers: {
    "operator acknowledgement missing": 1,
  },
  shadow_active_count: 1,
  reconciliation_needed_count: 1,
  ready_for_review_count: 1,
};

export const mockReviewSummary: ReviewSummaryView = {
  generated_at: "2026-03-15T11:30:00Z",
  overdue_reviews: 1,
  adherence_summary: {
    adherence_rate: 0.63,
    invalidation_discipline_rate: 0.5,
    review_completion_rate: 0.5,
  },
  failure_attribution_summary: {
    realism_ignored: 1,
    operator_timing: 1,
  },
  realism_warning_violations: 1,
  review_completion_trend: {
    review_backlog: 1,
    poor_adherence_streak: 1,
    reviewed_trade_count: 2,
  },
};

export const mockPilotSummary: PilotSummaryView = {
  generated_at: "2026-03-15T11:30:00Z",
  gate_state: mockExecutionGate.status,
  blockers: mockExecutionGate.blockers,
  ticket_funnel: mockPilotMetrics.ticket_conversion,
  divergence_metrics: mockPilotMetrics.shadow_metrics,
  adapter_health: mockAdapterHealth,
  audit_anomalies: mockAuditLogs,
  asset_class_trust_split: mockPilotDashboard.trust_by_asset_class,
};

export const mockStrategies: StrategyListView[] = [
  {
    name: "trend_breakout_v1",
    version: "1.0",
    template: "trend_breakout",
    description: "Daily BTC breakout strategy with trend confirmation.",
    underlying_symbol: "BTC",
    tradable_symbol: "BTC",
    timeframe: "1d",
    warmup_bars: 55,
    fees_bps: 8,
    slippage_bps: 5,
    proxy_grade: false,
    promoted: true,
    lifecycle_state: "promoted",
    lifecycle_updated_at: "2026-03-15T11:30:00Z",
    lifecycle_note: "Forward validation held up under fixture-mode penalties.",
    tags: ["trend", "breakout"],
    validation: { walk_forward_required: true, robustness_required: true },
    data_reality: btcDataReality,
  },
];

export const mockStrategyDetail: StrategyDetailView = {
  ...mockStrategies[0],
  search_space: {
    breakout_buffer: { kind: "float", low: 0, high: 0.02, step: 0.01 },
  },
  spec: {},
  promotion_rationale: {
    state: "promoted",
    recommended_state: "promoted",
    gate_results: {
      robustness_score: true,
      walk_forward_quality: true,
      forward_results: true,
      minimum_sample_size: true,
      data_quality: true,
      proxy_grade_penalty: true,
    },
    notes: ["Calibration buckets compare cohorts only. They are not probability-of-profit estimates.", "Total realism penalty: 38.0"],
    penalties: mockTrendPenalties,
  },
  operator_feedback_summary: {
    trade_count: 1,
    adherence_rate: 1,
    adherence_adjusted_expectancy_proxy: 3.58,
    realism_adjusted_expectancy_proxy: 1.72,
    operator_error_rate: 0,
    drift_indicator: "stable",
    dominant_failure_categories: [],
    notes: [
      "Adherence-adjusted expectancy proxy: +3.58%.",
      "Realism-adjusted expectancy proxy: +1.72%.",
      "Operator-error-tagged review share: 0.00.",
    ],
  },
  calibration_summary: mockCalibrationSummary,
  forward_validation_summary: {
    sample_size: 3,
    hit_rate: 0.67,
    expectancy_proxy: 1.0,
    drawdown: -1.12,
    target_attainment: 0.67,
    invalidation_rate: 0,
    time_stop_frequency: 0.33,
    modes: { paper_trade: 2, live_sim: 1 },
  },
  forward_validation_records: [
    {
      validation_id: "fv_trend_breakout_003",
      strategy_name: "trend_breakout_v1",
      mode: "live_sim",
      signal_id: mockSignals[0].signal_id,
      risk_report_id: mockRisk[0].risk_report_id,
      trade_id: null,
      opened_at: "2026-03-13T10:30:00Z",
      closed_at: "2026-03-14T12:00:00Z",
      entry_price: 71320,
      exit_price: 70990,
      pnl_pct: -0.46,
      drawdown_pct: -1.12,
      target_attained: false,
      invalidated: false,
      time_stopped: true,
      data_quality: "paper",
      notes: "Time-stop exit without invalidation.",
    },
    {
      validation_id: "fv_trend_breakout_002",
      strategy_name: "trend_breakout_v1",
      mode: "paper_trade",
      signal_id: mockSignals[0].signal_id,
      risk_report_id: mockRisk[0].risk_report_id,
      trade_id: null,
      opened_at: "2026-03-12T10:30:00Z",
      closed_at: "2026-03-13T13:00:00Z",
      entry_price: 70880,
      exit_price: 72110,
      pnl_pct: 1.74,
      drawdown_pct: -0.68,
      target_attained: true,
      invalidated: false,
      time_stopped: false,
      data_quality: "paper",
      notes: "Second paper validation leg reached the base target.",
    },
  ],
  data_realism_penalties: mockTrendPenalties,
  transition_history: [
    {
      strategy_name: "trend_breakout_v1",
      from_state: "paper_validating",
      to_state: "promoted",
      changed_at: "2026-03-15T11:30:00Z",
      note: "Forward validation met promotion gates in fixture mode.",
    },
    {
      strategy_name: "trend_breakout_v1",
      from_state: "experimental",
      to_state: "paper_validating",
      changed_at: "2026-03-14T11:30:00Z",
      note: "Initial paper validation cohort started.",
    },
  ],
};

export const mockBacktests: BacktestListView[] = [
  {
    id: 7,
    strategy_name: "trend_breakout_v1",
    engine: "strategy_lab",
    status: "completed",
    symbol: "BTC",
    timeframe: "1d",
    created_at: "2026-03-15T10:45:00Z",
    proxy_grade: false,
    promoted_candidate: false,
    search_method: "grid",
    robustness_score: 71.4,
    net_return_pct: 14.2,
    sharpe_ratio: 1.18,
    max_drawdown_pct: -8.6,
    trade_count: 7,
    lifecycle_state: "promoted",
    data_realism_penalties: mockTrendPenalties,
    data_reality: btcDataReality,
  },
];

export const mockBacktestDetail: BacktestDetailView = {
  ...mockBacktests[0],
  completed_at: "2026-03-15T10:46:00Z",
  fees_bps: 8,
  slippage_bps: 5,
  warmup_bars: 55,
  validation: {
    flags: { no_lookahead: true, time_series_split_only: true, walk_forward_required: true },
    walk_forward: { window_count: 3, positive_window_ratio: 0.67 },
  },
  summary: {
    best_parameters: { breakout_buffer: 0.01, relative_volume_min: 1.1 },
  },
  equity_curve: [
    { timestamp: "2026-03-01T00:00:00Z", equity: 100000 },
    { timestamp: "2026-03-05T00:00:00Z", equity: 104200 },
    { timestamp: "2026-03-10T00:00:00Z", equity: 111400 },
    { timestamp: "2026-03-15T00:00:00Z", equity: 114200 },
  ],
  trades: [
    { entry_time: "2026-03-03T00:00:00Z", exit_time: "2026-03-07T00:00:00Z", side: "long", entry_price: 69200, exit_price: 71110, pnl_pct: 2.76 },
  ],
  stability_heatmap: [
    {
      x_param: "relative_volume_min",
      y_param: "breakout_buffer",
      x_labels: ["1.0", "1.1", "1.2"],
      y_labels: ["0.00", "0.01", "0.02"],
      values: [
        [55.2, 60.4, 61.8],
        [58.1, 66.5, 68.2],
        [53.9, 62.3, 64.1],
      ],
    },
  ],
  regime_summary: [{ regime: "risk_on", return_pct: 14.2, trade_count: 7, win_rate: 0.71 }],
  metadata: {},
  promotion_rationale: mockStrategyDetail.promotion_rationale,
  forward_validation_summary: mockStrategyDetail.forward_validation_summary,
  calibration_summary: mockCalibrationSummary,
};
