import type {
  ActiveTradeView,
  AlertEnvelope,
  AssetContextView,
  BacktestDetailView,
  BacktestListView,
  BarView,
  DataRealityView,
  HealthView,
  JournalReviewView,
  NewsView,
  OpportunityHunterView,
  PaperTradeAnalyticsView,
  PaperTradeDetailView,
  PaperTradeReviewView,
  PaperTradeView,
  ResearchView,
  RibbonView,
  RiskDetailView,
  RiskExposureView,
  RiskView,
  SignalDetailView,
  SignalView,
  StrategyDetailView,
  StrategyListView,
  WalletBalanceView,
  WatchlistView,
} from "../types/api";

export const mockHealth: HealthView = {
  status: "mock",
  sqlite_path: "mock/sqlite.db",
  duckdb_path: "mock/analytics.duckdb",
  parquet_dir: "mock/parquet",
};

const btcDataReality: DataRealityView = {
  provenance: {
    symbol: "BTC",
    underlying_asset: "BTC",
    tradable_symbol: "BTCUSD",
    source_name: "fixture_bars",
    source_type: "fixture",
    freshness_sla_minutes: 1440,
    realism_grade: "B",
    proxy_mapping_notes: "Direct crypto spot mapping in fixture mode.",
    asset_class: "crypto",
  },
  freshness_minutes: 5,
  freshness_state: "fresh",
  realism_score: 52,
  ranking_penalty: 32,
  promotion_blocked: false,
  alert_allowed: true,
  ui_warning: "Current context is running in deterministic fixture-first mode.",
  penalties: [
    {
      code: "fixture_only",
      severity: "warning",
      summary: "Current context is running in deterministic fixture-first mode.",
      score_penalty: 14,
    },
    {
      code: "fixture_source",
      severity: "info",
      summary: "Source is fixture-backed rather than exchange-verified.",
      score_penalty: 18,
    },
  ],
  tradable_alignment_note: "BTC aligns directly with BTCUSD.",
};

const ethDataReality: DataRealityView = {
  provenance: {
    symbol: "ETH",
    underlying_asset: "ETH",
    tradable_symbol: "ETHUSD",
    source_name: "fixture_bars",
    source_type: "fixture",
    freshness_sla_minutes: 1440,
    realism_grade: "B",
    proxy_mapping_notes: "Direct crypto spot mapping in fixture mode.",
    asset_class: "crypto",
  },
  freshness_minutes: 5,
  freshness_state: "fresh",
  realism_score: 46,
  ranking_penalty: 38,
  promotion_blocked: false,
  alert_allowed: true,
  ui_warning: "Current context is running in deterministic fixture-first mode.",
  penalties: [
    {
      code: "fixture_only",
      severity: "warning",
      summary: "Current context is running in deterministic fixture-first mode.",
      score_penalty: 14,
    },
    {
      code: "fixture_source",
      severity: "info",
      summary: "Source is fixture-backed rather than exchange-verified.",
      score_penalty: 18,
    },
    {
      code: "missing_cross_asset_confirmation",
      severity: "info",
      summary: "Cross-asset confirmation is weak or missing in the latest context.",
      score_penalty: 6,
    },
  ],
  tradable_alignment_note: "ETH aligns directly with ETHUSD.",
};

const wtiDataReality: DataRealityView = {
  provenance: {
    symbol: "WTI",
    underlying_asset: "WTI",
    tradable_symbol: "USO",
    source_name: "macro_fixture_proxy",
    source_type: "proxy",
    freshness_sla_minutes: 1440,
    realism_grade: "D",
    proxy_mapping_notes: "WTI context is approximated through a proxy-grade local series.",
    asset_class: "commodity",
  },
  freshness_minutes: 10,
  freshness_state: "fresh",
  realism_score: 0,
  ranking_penalty: 64,
  promotion_blocked: true,
  alert_allowed: false,
  ui_warning:
    "WTI context is approximated through a proxy-grade local series. | Oil context is materially weaker than direct venue-grade futures data.",
  penalties: [
    {
      code: "fixture_only",
      severity: "warning",
      summary: "Current context is running in deterministic fixture-first mode.",
      score_penalty: 18,
    },
    {
      code: "proxy_grade_mapping",
      severity: "warning",
      summary: "WTI context is approximated through a proxy-grade local series.",
      score_penalty: 14,
    },
    {
      code: "tradable_mismatch",
      severity: "warning",
      summary: "Underlying WTI is represented through tradable proxy USO.",
      score_penalty: 8,
    },
    {
      code: "missing_cross_asset_confirmation",
      severity: "info",
      summary: "Cross-asset confirmation is weak or missing in the latest context.",
      score_penalty: 6,
    },
    {
      code: "weak_oil_realism",
      severity: "critical",
      summary: "Oil context is materially weaker than direct venue-grade futures data.",
      score_penalty: 18,
    },
  ],
  tradable_alignment_note: "WTI is mapped to tradable proxy USO.",
};

export const mockRibbon: RibbonView = {
  macro_regime: "event-risk",
  data_freshness_minutes: 22,
  freshness_status: "fresh",
  risk_budget_used_pct: 1.1,
  risk_budget_total_pct: 2.5,
  pipeline_status: "completed",
  source_mode: "sample",
  last_refresh: "2026-03-15T11:30:00Z",
  next_event: {
    title: "US CPI Release",
    impact: "high",
    event_time: "2026-03-15T12:30:00Z",
  },
};

export const mockSignals: SignalView[] = [
  {
    signal_id: "sig_8dca021b9c1256658b09a4fa6e218485",
    symbol: "BTC",
    signal_type: "trend_breakout",
    timestamp: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
    direction: "long",
    score: 74.6,
    confidence: 0.79,
    noise_probability: 0.22,
    thesis: "Breakout above the 20-day range remains intact with aligned structure and supportive volume.",
    invalidation: 68450,
    targets: { base: 73120, stretch: 74840 },
    uncertainty: 0.21,
    data_quality: "fixture",
    affected_assets: ["BTC", "ETH"],
    features: { close: 71880, atr_14: 1720, trend_state: "uptrend", relative_volume: 1.22, breakout_distance: 0.018, cross_asset_positive: ["ETH"] },
    data_reality: btcDataReality,
  },
  {
    signal_id: "sig_342ef03a8f4a559b9b1773fc5fd9f4ae",
    symbol: "ETH",
    signal_type: "event_driven",
    timestamp: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
    direction: "neutral",
    score: 31.4,
    confidence: 0.58,
    noise_probability: 0.41,
    thesis: "CPI is inside the event window. Continuation setups should be treated as event-sensitive until the release clears.",
    invalidation: 3440,
    targets: { base: 3745, stretch: 3810 },
    uncertainty: 0.42,
    data_quality: "fixture",
    affected_assets: ["ETH", "BTC"],
    features: { close: 3588, atr_14: 104, trend_state: "uptrend", relative_volume: 0.96, breakout_distance: 0.007, cross_asset_positive: [] },
    data_reality: ethDataReality,
  },
];

export const mockHighRiskSignals = mockSignals.filter((row) => row.noise_probability >= 0.35);

export const mockNews: NewsView[] = [
  {
    source: "EIA",
    published_at: "2026-03-15T10:10:00Z",
    freshness_minutes: 80,
    title: "Crude inventory draw tightens inflation-sensitive macro backdrop",
    summary: "Energy-led inflation context remains relevant for rates, dollar sensitivity, and crypto beta positioning.",
    url: "https://www.eia.gov/petroleum/supply/weekly/",
    tags: ["oil", "inflation", "macro"],
    entity_tags: ["oil", "inflation", "macro", "WTI", "US10Y", "BTC", "ETH"],
    affected_assets: ["WTI", "US10Y", "BTC", "ETH"],
    data_quality: "fixture",
  },
  {
    source: "FRED",
    published_at: "2026-03-15T09:00:00Z",
    freshness_minutes: 150,
    title: "CPI release due within the next hour",
    summary: "High-impact inflation data can reset rate expectations, dollar pricing, and crypto risk appetite.",
    url: "https://fred.stlouisfed.org/",
    tags: ["cpi", "rates", "macro"],
    entity_tags: ["cpi", "rates", "macro", "BTC", "ETH", "DXY", "US10Y"],
    affected_assets: ["BTC", "ETH", "DXY", "US10Y"],
    data_quality: "fixture",
  },
];

export const mockWatchlist: WatchlistView[] = [
  {
    symbol: "BTC",
    label: "Bitcoin",
    thesis: "Primary crypto beta with the cleanest breakout structure.",
    priority: 1,
    status: "active",
    last_signal_score: 74.6,
    updated_at: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
  },
  {
    symbol: "ETH",
    label: "Ethereum",
    thesis: "Watch for confirmation after the macro event clears.",
    priority: 2,
    status: "active",
    last_signal_score: 31.4,
    updated_at: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
  },
  {
    symbol: "WTI",
    label: "WTI Crude",
    thesis: "Macro scout asset for inflation spillover.",
    priority: 3,
    status: "context",
    last_signal_score: 0,
    updated_at: "2026-03-15T11:20:00Z",
    freshness_minutes: 10,
  },
];

export const mockResearch: ResearchView[] = [
  {
    symbol: "BTC",
    label: "BTC",
    timeframe: "1d",
    last_price: 71880,
    return_1d_pct: 1.42,
    return_5d_pct: 4.9,
    trend_state: "uptrend",
    relative_volume: 1.22,
    atr_pct: 2.4,
    breakout_distance: 1.8,
    structure_score: 2.4,
    data_quality: "fixture",
    data_reality: btcDataReality,
  },
  {
    symbol: "ETH",
    label: "ETH",
    timeframe: "1d",
    last_price: 3588,
    return_1d_pct: -0.6,
    return_5d_pct: 2.1,
    trend_state: "uptrend",
    relative_volume: 0.96,
    atr_pct: 2.9,
    breakout_distance: 0.7,
    structure_score: 1.4,
    data_quality: "fixture",
    data_reality: ethDataReality,
  },
  {
    symbol: "WTI",
    label: "WTI",
    timeframe: "1d",
    last_price: 79.2,
    return_1d_pct: 0.4,
    return_5d_pct: 1.2,
    trend_state: "range",
    relative_volume: 1.08,
    atr_pct: 1.9,
    breakout_distance: 0.2,
    structure_score: 0.8,
    data_quality: "fixture",
    data_reality: wtiDataReality,
  },
];

export const mockRisk: RiskView[] = [
  {
    risk_report_id: "risk_28782b441c135ccf921f5dbc7f3d6d77",
    signal_id: mockSignals[0].signal_id,
    symbol: "BTC",
    as_of: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
    stop_price: 68450,
    size_band: "medium",
    max_portfolio_risk_pct: 0.7,
    exposure_cluster: "crypto_beta",
    uncertainty: 0.21,
    data_quality: "fixture",
    scenario_shocks: { risk_off_pct: -8, liquidity_gap_pct: -4.5, macro_repricing_pct: -6 },
    report: { entry_reference: 71880, atr_14: 1720, risk_notes: ["No live execution enabled."] },
    data_reality: btcDataReality,
  },
  {
    risk_report_id: "risk_3490fc4bf0305fbcbe6c1765fcc4fed8",
    signal_id: mockSignals[1].signal_id,
    symbol: "ETH",
    as_of: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
    stop_price: 3440,
    size_band: "small",
    max_portfolio_risk_pct: 0.4,
    exposure_cluster: "crypto_beta",
    uncertainty: 0.42,
    data_quality: "fixture",
    scenario_shocks: { risk_off_pct: -10.5, liquidity_gap_pct: -5.8, macro_repricing_pct: -7.2 },
    report: { entry_reference: 3588, atr_14: 104, risk_notes: ["Reduce conviction near CPI."] },
    data_reality: ethDataReality,
  },
];

export const mockRiskExposure: RiskExposureView[] = [
  {
    cluster: "crypto_beta",
    symbols: ["BTC", "ETH"],
    gross_risk_pct: 1.1,
    worst_scenario_pct: -10.5,
  },
];

const mockTrendPenalties = [
  {
    code: "fixture_only",
    severity: "warning",
    summary: "Current validation depends on fixture-first market data.",
    score_penalty: 14,
  },
  {
    code: "missing_cross_asset_confirmation",
    severity: "info",
    summary: "Cross-asset confirmation is weak or missing in the latest context.",
    score_penalty: 6,
  },
];

const mockCalibrationSummary = [
  {
    strategy_name: "trend_breakout_v1",
    created_at: "2026-03-15T11:30:00Z",
    bucket_kind: "score",
    buckets: [
      { bucket: "top", sample_size: 3, avg_score: 74.6, avg_confidence: 0.79, hit_rate: 0.67, expectancy_proxy: 1.0, invalidation_rate: 0, target_attainment: 0.67 },
      { bucket: "middle", sample_size: 0, avg_score: 0, avg_confidence: 0, hit_rate: 0, expectancy_proxy: 0, invalidation_rate: 0, target_attainment: 0 },
      { bucket: "low", sample_size: 0, avg_score: 0, avg_confidence: 0, hit_rate: 0, expectancy_proxy: 0, invalidation_rate: 0, target_attainment: 0 },
    ],
    notes: "Calibration compares buckets only. It is not a probability-of-profit claim.",
  },
  {
    strategy_name: "trend_breakout_v1",
    created_at: "2026-03-15T11:30:00Z",
    bucket_kind: "confidence",
    buckets: [
      { bucket: "top", sample_size: 3, avg_score: 74.6, avg_confidence: 0.79, hit_rate: 0.67, expectancy_proxy: 1.0, invalidation_rate: 0, target_attainment: 0.67 },
      { bucket: "middle", sample_size: 0, avg_score: 0, avg_confidence: 0, hit_rate: 0, expectancy_proxy: 0, invalidation_rate: 0, target_attainment: 0 },
      { bucket: "low", sample_size: 0, avg_score: 0, avg_confidence: 0, hit_rate: 0, expectancy_proxy: 0, invalidation_rate: 0, target_attainment: 0 },
    ],
    notes: "Calibration compares buckets only. It is not a probability-of-profit claim.",
  },
];

export const mockSignalDetail: SignalDetailView = {
  ...mockSignals[0],
  evidence: [
    {
      label: "Breakout distance",
      value: "1.8%",
      verdict: "supportive",
      note: "Distance above the recent breakout level.",
    },
    {
      label: "Relative volume",
      value: "1.22x",
      verdict: "supportive",
      note: "Current volume is above the 20-bar baseline.",
    },
  ],
  catalyst_news: mockNews,
  related_risk: mockRisk[0],
  freshness_status: "fresh",
};

export const mockRiskDetail: RiskDetailView = {
  ...mockRisk[0],
  linked_signal: mockSignals[0],
  stop_logic: {
    method: "atr_multiple",
    entry_reference: 71880,
    atr_14: 1720,
    stop_price: 68450,
    distance: 3430,
  },
  risk_notes: ["No live execution enabled."],
  cluster_exposure: mockRiskExposure[0],
  freshness_status: "fresh",
};

export const mockOpportunities: OpportunityHunterView = {
  generated_at: "2026-03-15T11:30:00Z",
  focus_queue: [
    {
      symbol: "BTC",
      label: "Bitcoin",
      queue: "focus",
      score: 90.45,
      score_decomposition: {
        signal_score: 74.6,
        confidence_bonus: 11.85,
        trend_bonus: 6,
        noise_penalty: 3.96,
        freshness_penalty: 0.08,
        realism_penalty: 32,
      },
      promotion_reasons: ["signal_score_above_focus_threshold", "trend_state_uptrend", "risk_budget_acceptable"],
      freshness_minutes: 5,
      risk_notes: ["No live execution enabled."],
      signal_id: mockSignals[0].signal_id,
      risk_report_id: mockRisk[0].risk_report_id,
      status: "active",
      data_reality: btcDataReality,
    },
  ],
  scout_queue: [
    {
      symbol: "ETH",
      label: "Ethereum",
      queue: "scout",
      score: 39.4,
      score_decomposition: {
        signal_score: 31.4,
        confidence_bonus: 8.7,
        trend_bonus: 6,
        noise_penalty: 7.38,
        freshness_penalty: 0.08,
        realism_penalty: 38,
      },
      promotion_reasons: ["trend_state_uptrend", "awaiting_confirmation"],
      freshness_minutes: 5,
      risk_notes: ["Reduce conviction near CPI."],
      signal_id: mockSignals[1].signal_id,
      risk_report_id: mockRisk[1].risk_report_id,
      status: "active",
      data_reality: ethDataReality,
    },
  ],
};

export const mockBars: Record<string, BarView[]> = {
  BTC: [
    { symbol: "BTC", timestamp: "2026-03-11T00:00:00Z", open: 69210, high: 69920, low: 68880, close: 69740, volume: 22800 },
    { symbol: "BTC", timestamp: "2026-03-12T00:00:00Z", open: 69740, high: 70640, low: 69520, close: 70420, volume: 24100 },
    { symbol: "BTC", timestamp: "2026-03-13T00:00:00Z", open: 70420, high: 71310, low: 70110, close: 70980, volume: 25220 },
    { symbol: "BTC", timestamp: "2026-03-14T00:00:00Z", open: 70980, high: 72140, low: 70710, close: 71880, volume: 26740 },
  ],
  ETH: [
    { symbol: "ETH", timestamp: "2026-03-11T00:00:00Z", open: 3522, high: 3570, low: 3498, close: 3554, volume: 140200 },
    { symbol: "ETH", timestamp: "2026-03-12T00:00:00Z", open: 3554, high: 3638, low: 3531, close: 3622, volume: 146400 },
    { symbol: "ETH", timestamp: "2026-03-13T00:00:00Z", open: 3622, high: 3640, low: 3572, close: 3588, volume: 131100 },
    { symbol: "ETH", timestamp: "2026-03-14T00:00:00Z", open: 3588, high: 3612, low: 3525, close: 3566, volume: 125480 },
  ],
  WTI: [
    { symbol: "WTI", timestamp: "2026-03-11T00:00:00Z", open: 78.1, high: 79.0, low: 77.8, close: 78.6, volume: 7120 },
    { symbol: "WTI", timestamp: "2026-03-12T00:00:00Z", open: 78.6, high: 79.3, low: 78.2, close: 79.0, volume: 7340 },
    { symbol: "WTI", timestamp: "2026-03-13T00:00:00Z", open: 79.0, high: 79.7, low: 78.7, close: 79.2, volume: 7280 },
    { symbol: "WTI", timestamp: "2026-03-14T00:00:00Z", open: 79.2, high: 79.6, low: 78.4, close: 78.9, volume: 7400 },
  ],
};

export const mockAssetContexts: Record<string, AssetContextView> = {
  BTC: {
    symbol: "BTC",
    latest_signal: mockSignals[0],
    latest_risk: mockRisk[0],
    research: mockResearch[0],
    related_news: mockNews,
    latest_backtest: {
      id: 7,
      strategy_name: "trend_breakout_v1",
      engine: "strategy_lab",
      status: "completed",
      symbol: "BTC",
      timeframe: "1d",
      created_at: "2026-03-15T10:45:00Z",
      proxy_grade: false,
      promoted_candidate: false,
      search_method: "grid",
      robustness_score: 71.4,
      net_return_pct: 14.2,
      sharpe_ratio: 1.18,
      max_drawdown_pct: -8.6,
      trade_count: 7,
      lifecycle_state: "promoted",
      data_realism_penalties: mockTrendPenalties,
      data_reality: btcDataReality,
    },
    data_reality: btcDataReality,
  },
  ETH: {
    symbol: "ETH",
    latest_signal: mockSignals[1],
    latest_risk: mockRisk[1],
    research: mockResearch[1],
    related_news: mockNews,
    latest_backtest: null,
    data_reality: ethDataReality,
  },
  WTI: {
    symbol: "WTI",
    latest_signal: null,
    latest_risk: null,
    research: mockResearch[2],
    related_news: mockNews.filter((item) => item.affected_assets.includes("WTI")),
    latest_backtest: null,
    data_reality: wtiDataReality,
  },
};

export const mockActiveTrades: ActiveTradeView[] = [
  {
    trade_id: "trade_c5093f1b8d175f7e9ac0e6a5fd6151f8",
    symbol: "BTC",
    strategy_name: "trend_breakout_v1",
    side: "long",
    entry_time: "2026-03-12T10:30:00Z",
    entry_price: 70420,
    current_price: 71880,
    stop_price: 68450,
    target_price: 74200,
    pnl_pct: 2.07,
    size_band: "medium",
    status: "open",
    thesis: "Breakout structure remains valid above invalidation.",
    data_quality: "fixture",
    signal_id: mockSignals[0].signal_id,
    risk_report_id: mockRisk[0].risk_report_id,
    notes: "Trim size if CPI lands hotter than expected.",
    updated_at: "2026-03-15T11:25:00Z",
    freshness_minutes: 5,
  },
];

export const mockPaperTradesProposed: PaperTradeView[] = [
  {
    trade_id: "paper_trade_proposed_btc",
    signal_id: mockSignals[0].signal_id,
    risk_report_id: mockRisk[0].risk_report_id,
    strategy_id: "trend_breakout_v1",
    symbol: "BTC",
    side: "long",
    proposed_entry_zone: { low: 71320, high: 72440 },
    actual_entry: null,
    stop: 68450,
    targets: { base: 73120, stretch: 74840 },
    size_plan: { size_band: "medium", max_portfolio_risk_pct: 0.7 },
    actual_size: 0,
    status: "proposed",
    opened_at: null,
    closed_at: null,
    close_reason: "",
    close_price: null,
    notes: "Candidate breakout entry queued from the ranked BTC signal.",
    freshness_minutes: 4,
    data_quality: "fixture",
    lifecycle_events: [
      { status: "proposed", note: "Proposed from BTC trend breakout signal.", timestamp: "2026-03-15T11:26:00Z" },
    ],
    outcome: {
      entry_quality_label: "pending",
      entry_zone_delta_pct: 0,
      stop_adherence: true,
      target_attainment: "none",
      time_to_outcome_minutes: 0,
      mfe_pct: 0,
      mae_pct: 0,
      plan_adherence_flags: { entry_in_zone: false, size_defined: true, target_reached: false, stop_respected: true },
      realized_pnl_pct: 0,
    },
    review_due: false,
    data_reality: btcDataReality,
  },
];

export const mockPaperTradesActive: PaperTradeView[] = [
  {
    trade_id: "paper_trade_open_eth",
    signal_id: mockSignals[1].signal_id,
    risk_report_id: mockRisk[1].risk_report_id,
    strategy_id: "event_continuation_v1",
    symbol: "ETH",
    side: "long",
    proposed_entry_zone: { low: 3555, high: 3610 },
    actual_entry: 3595,
    stop: 3440,
    targets: { base: 3745, stretch: 3810 },
    size_plan: { size_band: "small", max_portfolio_risk_pct: 0.4 },
    actual_size: 1.2,
    status: "opened",
    opened_at: "2026-03-12T10:30:00Z",
    closed_at: null,
    close_reason: "",
    close_price: null,
    notes: "Event-sensitive continuation probe remains open into macro follow-through.",
    freshness_minutes: 2880,
    data_quality: "paper",
    lifecycle_events: [
      { status: "proposed", note: "Proposed from event continuation signal.", timestamp: "2026-03-12T09:45:00Z" },
      { status: "opened", note: "Opened with reduced size because event risk remained elevated.", timestamp: "2026-03-12T10:30:00Z" },
    ],
    outcome: {
      entry_quality_label: "inside_zone",
      entry_zone_delta_pct: 0.35,
      stop_adherence: true,
      target_attainment: "none",
      time_to_outcome_minutes: 4380,
      mfe_pct: 1.25,
      mae_pct: -1.95,
      plan_adherence_flags: { entry_in_zone: true, size_defined: true, target_reached: false, stop_respected: true },
      realized_pnl_pct: -0.81,
    },
    review_due: false,
    data_reality: ethDataReality,
  },
];

export const mockPaperTradesClosed: PaperTradeView[] = [
  {
    trade_id: "paper_trade_closed_btc",
    signal_id: mockSignals[0].signal_id,
    risk_report_id: mockRisk[0].risk_report_id,
    strategy_id: "trend_breakout_v1",
    symbol: "BTC",
    side: "long",
    proposed_entry_zone: { low: 70480, high: 70980 },
    actual_entry: 70620,
    stop: 68450,
    targets: { base: 73120, stretch: 74840 },
    size_plan: { size_band: "medium", max_portfolio_risk_pct: 0.7 },
    actual_size: 0,
    status: "closed_win",
    opened_at: "2026-03-11T10:30:00Z",
    closed_at: "2026-03-12T14:00:00Z",
    close_reason: "target_hit",
    close_price: 73150,
    notes: "Base target filled after orderly follow-through.",
    freshness_minutes: 4260,
    data_quality: "paper",
    lifecycle_events: [
      { status: "proposed", note: "Proposed from BTC signal.", timestamp: "2026-03-11T09:55:00Z" },
      { status: "opened", note: "Opened after intraday reclaim.", timestamp: "2026-03-11T10:30:00Z" },
      { status: "closed_win", note: "Closed at base target.", timestamp: "2026-03-12T14:00:00Z" },
    ],
    outcome: {
      entry_quality_label: "inside_zone",
      entry_zone_delta_pct: 0.2,
      stop_adherence: true,
      target_attainment: "base",
      time_to_outcome_minutes: 1650,
      mfe_pct: 3.9,
      mae_pct: -0.82,
      plan_adherence_flags: { entry_in_zone: true, size_defined: true, target_reached: true, stop_respected: true },
      realized_pnl_pct: 3.58,
    },
    review_due: false,
    data_reality: btcDataReality,
  },
  {
    trade_id: "paper_trade_invalidated_eth",
    signal_id: mockSignals[1].signal_id,
    risk_report_id: mockRisk[1].risk_report_id,
    strategy_id: "vol_expansion_v1",
    symbol: "ETH",
    side: "long",
    proposed_entry_zone: { low: 3560, high: 3605 },
    actual_entry: 3582,
    stop: 3440,
    targets: { base: 3745, stretch: 3810 },
    size_plan: { size_band: "small", max_portfolio_risk_pct: 0.4 },
    actual_size: 0,
    status: "invalidated",
    opened_at: "2026-03-10T13:00:00Z",
    closed_at: "2026-03-10T18:00:00Z",
    close_reason: "invalidated",
    close_price: 3440,
    notes: "Macro release reversed the setup and invalidation was hit.",
    freshness_minutes: 6780,
    data_quality: "paper",
    lifecycle_events: [
      { status: "proposed", note: "Proposed from ETH event-sensitive setup.", timestamp: "2026-03-10T12:30:00Z" },
      { status: "opened", note: "Opened before the release window.", timestamp: "2026-03-10T13:00:00Z" },
      { status: "invalidated", note: "Exited at invalidation after macro reversal.", timestamp: "2026-03-10T18:00:00Z" },
    ],
    outcome: {
      entry_quality_label: "inside_zone",
      entry_zone_delta_pct: -0.01,
      stop_adherence: true,
      target_attainment: "none",
      time_to_outcome_minutes: 300,
      mfe_pct: 0.45,
      mae_pct: -4.02,
      plan_adherence_flags: { entry_in_zone: true, size_defined: true, target_reached: false, stop_respected: true },
      realized_pnl_pct: -3.96,
    },
    review_due: true,
    data_reality: ethDataReality,
  },
];

export const mockPaperTradeReviews: PaperTradeReviewView[] = [
  {
    review_id: "paper_review_closed_btc",
    trade_id: "paper_trade_closed_btc",
    thesis_respected: true,
    invalidation_respected: true,
    entered_too_early: false,
    entered_too_late: false,
    oversized: false,
    undersized: false,
    realism_warning_ignored: false,
    catalyst_mattered: true,
    failure_category: "",
    operator_notes: "Execution stayed inside the planned zone and the base target exit respected the original thesis.",
    updated_at: "2026-03-12T16:00:00Z",
  },
];

export const mockPaperTradeDetail: PaperTradeDetailView = {
  ...mockPaperTradesClosed[0],
  linked_signal: mockSignals[0],
  linked_risk: mockRisk[0],
  review: mockPaperTradeReviews[0],
};

export const mockPaperTradeAnalytics: PaperTradeAnalyticsView = {
  generated_at: "2026-03-15T11:30:00Z",
  by_signal_family: [
    {
      grouping: "signal_family",
      key: "trend_breakout",
      trade_count: 1,
      hit_rate: 1,
      expectancy_proxy: 3.58,
      target_attainment_rate: 1,
      invalidation_rate: 0,
      avg_entry_zone_delta_pct: 0.2,
      avg_mfe_pct: 3.9,
      avg_mae_pct: -0.82,
    },
    {
      grouping: "signal_family",
      key: "event_driven",
      trade_count: 1,
      hit_rate: 0,
      expectancy_proxy: -3.96,
      target_attainment_rate: 0,
      invalidation_rate: 1,
      avg_entry_zone_delta_pct: -0.01,
      avg_mfe_pct: 0.45,
      avg_mae_pct: -4.02,
    },
  ],
  by_strategy: [
    {
      grouping: "strategy",
      key: "trend_breakout_v1",
      trade_count: 1,
      hit_rate: 1,
      expectancy_proxy: 3.58,
      target_attainment_rate: 1,
      invalidation_rate: 0,
      avg_entry_zone_delta_pct: 0.2,
      avg_mfe_pct: 3.9,
      avg_mae_pct: -0.82,
    },
    {
      grouping: "strategy",
      key: "vol_expansion_v1",
      trade_count: 1,
      hit_rate: 0,
      expectancy_proxy: -3.96,
      target_attainment_rate: 0,
      invalidation_rate: 1,
      avg_entry_zone_delta_pct: -0.01,
      avg_mfe_pct: 0.45,
      avg_mae_pct: -4.02,
    },
  ],
  by_score_bucket: [
    {
      grouping: "score_bucket",
      key: "low",
      trade_count: 1,
      hit_rate: 0,
      expectancy_proxy: -3.96,
      target_attainment_rate: 0,
      invalidation_rate: 1,
      avg_entry_zone_delta_pct: -0.01,
      avg_mfe_pct: 0.45,
      avg_mae_pct: -4.02,
    },
    {
      grouping: "score_bucket",
      key: "top",
      trade_count: 1,
      hit_rate: 1,
      expectancy_proxy: 3.58,
      target_attainment_rate: 1,
      invalidation_rate: 0,
      avg_entry_zone_delta_pct: 0.2,
      avg_mfe_pct: 3.9,
      avg_mae_pct: -0.82,
    },
  ],
  by_realism_bucket: [
    {
      grouping: "realism_bucket",
      key: "strong",
      trade_count: 1,
      hit_rate: 1,
      expectancy_proxy: 3.58,
      target_attainment_rate: 1,
      invalidation_rate: 0,
      avg_entry_zone_delta_pct: 0.2,
      avg_mfe_pct: 3.9,
      avg_mae_pct: -0.82,
    },
    {
      grouping: "realism_bucket",
      key: "usable",
      trade_count: 1,
      hit_rate: 0,
      expectancy_proxy: -3.96,
      target_attainment_rate: 0,
      invalidation_rate: 1,
      avg_entry_zone_delta_pct: -0.01,
      avg_mfe_pct: 0.45,
      avg_mae_pct: -4.02,
    },
  ],
  by_asset: [
    {
      grouping: "asset",
      key: "BTC",
      trade_count: 1,
      hit_rate: 1,
      expectancy_proxy: 3.58,
      target_attainment_rate: 1,
      invalidation_rate: 0,
      avg_entry_zone_delta_pct: 0.2,
      avg_mfe_pct: 3.9,
      avg_mae_pct: -0.82,
    },
    {
      grouping: "asset",
      key: "ETH",
      trade_count: 1,
      hit_rate: 0,
      expectancy_proxy: -3.96,
      target_attainment_rate: 0,
      invalidation_rate: 1,
      avg_entry_zone_delta_pct: -0.01,
      avg_mfe_pct: 0.45,
      avg_mae_pct: -4.02,
    },
  ],
};

export const mockWalletBalances: WalletBalanceView[] = [
  {
    venue: "paper",
    account_label: "Research Book",
    updated_at: "2026-03-15T09:15:00Z",
    total_usd: 125640,
    available_usd: 81420,
    data_quality: "fixture",
    balances: [
      { asset: "USD", free: 81420, locked: 0, usd_value: 81420 },
      { asset: "BTC", free: 0.42, locked: 0, usd_value: 30190 },
      { asset: "ETH", free: 3.9, locked: 0.6, usd_value: 14030 },
    ],
  },
];

export const mockJournal: JournalReviewView[] = [
  {
    journal_id: "journal_932840b8f8e95d8fa3c71ecf12ef7382",
    symbol: "BTC",
    entered_at: "2026-03-11T15:00:00Z",
    entry_type: "review",
    note: "Trend quality improved after reclaiming the 20-day breakout level, but CPI kept conviction moderate.",
    mood: "disciplined",
    tags: ["trend", "macro", "btc"],
    signal_id: mockSignals[0].signal_id,
    risk_report_id: mockRisk[0].risk_report_id,
    trade_id: mockActiveTrades[0].trade_id,
    setup_quality: 4,
    execution_quality: 4,
    follow_through: "held core and respected event-risk trim plan",
    outcome: "open",
    lessons: "Cap size to medium when a high-impact macro release is inside 24h.",
    review_status: "in_review",
    updated_at: "2026-03-15T11:20:00Z",
    freshness_minutes: 10,
  },
];

export const mockAlerts: AlertEnvelope[] = [
  {
    alert_id: "alert_1",
    created_at: "2026-03-15T11:25:00Z",
    signal_id: mockSignals[0].signal_id,
    risk_report_id: mockRisk[0].risk_report_id,
    asset_ids: ["BTC", "ETH"],
    severity: "info",
    category: "signal_ranked",
    channel_targets: ["in_app", "discord"],
    title: "BTC signal created",
    body: "Breakout above the 20-day range remains intact with aligned structure and supportive volume.",
    tags: ["trend_breakout", "long", "BTC"],
    dedupe_key: `signal_ranked:${mockSignals[0].signal_id}`,
    status: "sent",
    delivery_metadata: { sent_channels: ["in_app", "discord"], failed_channels: [] },
    data_quality: "fixture",
    suppressed_reason: null,
  },
  {
    alert_id: "alert_2",
    created_at: "2026-03-15T11:25:00Z",
    signal_id: mockSignals[1].signal_id,
    risk_report_id: mockRisk[1].risk_report_id,
    asset_ids: ["ETH", "BTC"],
    severity: "warning",
    category: "high_risk_signal",
    channel_targets: ["in_app", "telegram", "discord"],
    title: "ETH marked high risk",
    body: "Noise 41% with uncertainty 0.42.",
    tags: ["high-risk", "event_driven", "ETH"],
    dedupe_key: `high_risk_signal:${mockSignals[1].signal_id}`,
    status: "failed",
    delivery_metadata: { sent_channels: ["in_app"], failed_channels: ["telegram", "discord"] },
    data_quality: "fixture",
    suppressed_reason: null,
  },
  {
    alert_id: "alert_3",
    created_at: "2026-03-15T11:30:00Z",
    signal_id: null,
    risk_report_id: null,
    asset_ids: [],
    severity: "info",
    category: "daily_digest_summary",
    channel_targets: ["in_app"],
    title: "Daily operator digest",
    body: "Signals 2, focus queue 1, risk budget 1.100/2.500. Lead signal: BTC trend_breakout score 74.6.",
    tags: ["daily-digest", "sample"],
    dedupe_key: "daily_digest:2026-03-15",
    status: "suppressed",
    delivery_metadata: { suppressed_by: "alert_1", reason: "dedupe_window" },
    data_quality: "fixture",
    suppressed_reason: "dedupe_window",
  },
  {
    alert_id: "alert_4",
    created_at: "2026-03-15T11:30:00Z",
    signal_id: mockSignals[1].signal_id,
    risk_report_id: mockRisk[1].risk_report_id,
    asset_ids: ["ETH"],
    severity: "warning",
    category: "paper_trade_review_due",
    channel_targets: ["in_app"],
    title: "ETH review due",
    body: "Closed paper trade paper_trade_invalidated_eth is awaiting structured review.",
    tags: ["ETH", "invalidated", "paper_trade_review_due"],
    dedupe_key: "paper_trade_review_due:paper_trade_invalidated_eth:invalidated",
    status: "sent",
    delivery_metadata: { sent_channels: ["in_app"], failed_channels: [] },
    data_quality: "paper",
    suppressed_reason: null,
  },
];

export const mockStrategies: StrategyListView[] = [
  {
    name: "trend_breakout_v1",
    version: "1.0",
    template: "trend_breakout",
    description: "Daily BTC breakout strategy with trend confirmation.",
    underlying_symbol: "BTC",
    tradable_symbol: "BTC",
    timeframe: "1d",
    warmup_bars: 55,
    fees_bps: 8,
    slippage_bps: 5,
    proxy_grade: false,
    promoted: true,
    lifecycle_state: "promoted",
    lifecycle_updated_at: "2026-03-15T11:30:00Z",
    lifecycle_note: "Forward validation held up under fixture-mode penalties.",
    tags: ["trend", "breakout"],
    validation: { walk_forward_required: true, robustness_required: true },
    data_reality: btcDataReality,
  },
];

export const mockStrategyDetail: StrategyDetailView = {
  ...mockStrategies[0],
  search_space: {
    breakout_buffer: { kind: "float", low: 0, high: 0.02, step: 0.01 },
  },
  spec: {},
  promotion_rationale: {
    state: "promoted",
    recommended_state: "promoted",
    gate_results: {
      robustness_score: true,
      walk_forward_quality: true,
      forward_results: true,
      minimum_sample_size: true,
      data_quality: true,
      proxy_grade_penalty: true,
    },
    notes: ["Calibration buckets compare cohorts only. They are not probability-of-profit estimates.", "Total realism penalty: 20.0"],
    penalties: mockTrendPenalties,
  },
  calibration_summary: mockCalibrationSummary,
  forward_validation_summary: {
    sample_size: 3,
    hit_rate: 0.67,
    expectancy_proxy: 1.0,
    drawdown: -1.12,
    target_attainment: 0.67,
    invalidation_rate: 0,
    time_stop_frequency: 0.33,
    modes: { paper_trade: 2, live_sim: 1 },
  },
  forward_validation_records: [
    {
      validation_id: "fv_trend_breakout_003",
      strategy_name: "trend_breakout_v1",
      mode: "live_sim",
      signal_id: mockSignals[0].signal_id,
      risk_report_id: mockRisk[0].risk_report_id,
      trade_id: null,
      opened_at: "2026-03-13T10:30:00Z",
      closed_at: "2026-03-14T12:00:00Z",
      entry_price: 71320,
      exit_price: 70990,
      pnl_pct: -0.46,
      drawdown_pct: -1.12,
      target_attained: false,
      invalidated: false,
      time_stopped: true,
      data_quality: "paper",
      notes: "Time-stop exit without invalidation.",
    },
    {
      validation_id: "fv_trend_breakout_002",
      strategy_name: "trend_breakout_v1",
      mode: "paper_trade",
      signal_id: mockSignals[0].signal_id,
      risk_report_id: mockRisk[0].risk_report_id,
      trade_id: null,
      opened_at: "2026-03-12T10:30:00Z",
      closed_at: "2026-03-13T13:00:00Z",
      entry_price: 70880,
      exit_price: 72110,
      pnl_pct: 1.74,
      drawdown_pct: -0.68,
      target_attained: true,
      invalidated: false,
      time_stopped: false,
      data_quality: "paper",
      notes: "Second paper validation leg reached the base target.",
    },
  ],
  data_realism_penalties: mockTrendPenalties,
  transition_history: [
    {
      strategy_name: "trend_breakout_v1",
      from_state: "paper_validating",
      to_state: "promoted",
      changed_at: "2026-03-15T11:30:00Z",
      note: "Forward validation met promotion gates in fixture mode.",
    },
    {
      strategy_name: "trend_breakout_v1",
      from_state: "experimental",
      to_state: "paper_validating",
      changed_at: "2026-03-14T11:30:00Z",
      note: "Initial paper validation cohort started.",
    },
  ],
};

export const mockBacktests: BacktestListView[] = [
  {
    id: 7,
    strategy_name: "trend_breakout_v1",
    engine: "strategy_lab",
    status: "completed",
    symbol: "BTC",
    timeframe: "1d",
    created_at: "2026-03-15T10:45:00Z",
    proxy_grade: false,
    promoted_candidate: false,
    search_method: "grid",
    robustness_score: 71.4,
    net_return_pct: 14.2,
    sharpe_ratio: 1.18,
    max_drawdown_pct: -8.6,
    trade_count: 7,
    lifecycle_state: "promoted",
    data_realism_penalties: mockTrendPenalties,
    data_reality: btcDataReality,
  },
];

export const mockBacktestDetail: BacktestDetailView = {
  ...mockBacktests[0],
  completed_at: "2026-03-15T10:46:00Z",
  fees_bps: 8,
  slippage_bps: 5,
  warmup_bars: 55,
  validation: {
    flags: { no_lookahead: true, time_series_split_only: true, walk_forward_required: true },
    walk_forward: { window_count: 3, positive_window_ratio: 0.67 },
  },
  summary: {
    best_parameters: { breakout_buffer: 0.01, relative_volume_min: 1.1 },
  },
  equity_curve: [
    { timestamp: "2026-03-01T00:00:00Z", equity: 100000 },
    { timestamp: "2026-03-05T00:00:00Z", equity: 104200 },
    { timestamp: "2026-03-10T00:00:00Z", equity: 111400 },
    { timestamp: "2026-03-15T00:00:00Z", equity: 114200 },
  ],
  trades: [
    { entry_time: "2026-03-03T00:00:00Z", exit_time: "2026-03-07T00:00:00Z", side: "long", entry_price: 69200, exit_price: 71110, pnl_pct: 2.76 },
  ],
  stability_heatmap: [
    {
      x_param: "relative_volume_min",
      y_param: "breakout_buffer",
      x_labels: ["1.0", "1.1", "1.2"],
      y_labels: ["0.00", "0.01", "0.02"],
      values: [
        [55.2, 60.4, 61.8],
        [58.1, 66.5, 68.2],
        [53.9, 62.3, 64.1],
      ],
    },
  ],
  regime_summary: [{ regime: "risk_on", return_pct: 14.2, trade_count: 7, win_rate: 0.71 }],
  metadata: {},
  promotion_rationale: mockStrategyDetail.promotion_rationale,
  forward_validation_summary: mockStrategyDetail.forward_validation_summary,
  calibration_summary: mockCalibrationSummary,
};
